// Generated by scripts/build-starter-library.mjs. Do not edit.
export default [{"path":"human","name":"Human","cat":"People"},{"path":"goat_kid","name":"Goat Kid","cat":"Creatures"},{"path":"blue_robot","name":"Blue Robot","cat":"Robots"}];
