import test from 'node:test';
import assert from 'node:assert/strict';
import {createEditorNavigation} from '../engine/editor/navigation.mjs';
function fixture(state={}){const current={dirty:true,busy:false,mode:'edit',...state},events=[];const flow=createEditorNavigation({getState:()=>current,stop:async()=>{events.push('stop');current.mode='edit';},save:async()=>{events.push('save');current.dirty=false;},approve:value=>events.push(['approve',value]),navigate:async href=>events.push(['navigate',href])});return {flow,current,events};}
test('dirty project asks before any navigation or save',async()=>{const {flow,events}=fixture();assert.deepEqual(await flow.request('/games'),{needsSave:true});assert.equal(flow.pending,'/games');assert.deepEqual(events,[]);});
test('cancel preserves the dirty project and current page',async()=>{const {flow,current,events}=fixture();await flow.request('/games');flow.cancel();assert.equal(flow.pending,null);assert.equal(current.dirty,true);assert.deepEqual(events,[]);});
test('save and continue waits for Stop and durable Save before navigation',async()=>{const {flow,events}=fixture({mode:'play'});await flow.request('/games');await flow.saveAndLeave();assert.deepEqual(events,['stop','save',['approve',true],['navigate','/games']]);assert.equal(flow.pending,null);});
test('explicit leave without saving does not falsely mark project saved',async()=>{const {flow,current,events}=fixture();await flow.request('/games');await flow.leaveWithoutSaving();assert.equal(current.dirty,true);assert.deepEqual(events,[['approve',true],['navigate','/games']]);});
test('clean project may leave without a redundant prompt',async()=>{const {flow,events}=fixture({dirty:false});assert.deepEqual(await flow.request('/'),{needsSave:false});assert.deepEqual(events,[['approve',true],['navigate','/']]);});
test('clean Play stops before leaving',async()=>{const {flow,events}=fixture({dirty:false,mode:'play'});await flow.request('/');assert.equal(events[0],'stop');});
test('a busy editor cannot be navigated away by the guard',async()=>{const {flow,events}=fixture({busy:true});await assert.rejects(flow.request('/games'),/Wait/);assert.deepEqual(events,[]);});
test('failed save retains destination, dirty data, and retry; never navigates',async()=>{const state={dirty:true,mode:'edit'},events=[];let fail=true;const flow=createEditorNavigation({getState:()=>state,stop:async()=>{},save:async()=>{if(fail)throw new Error('Storage full');state.dirty=false;},approve:v=>events.push(v),navigate:async()=>events.push('left')});await flow.request('/games');await assert.rejects(flow.saveAndLeave(),/Storage full/);assert.equal(flow.pending,'/games');assert.equal(state.dirty,true);assert.deepEqual(events,[false]);fail=false;await flow.saveAndLeave();assert.deepEqual(events,[false,true,'left']);});
test('double confirmation cannot save or navigate twice',async()=>{let resolveSave;const events=[];const flow=createEditorNavigation({getState:()=>({dirty:true,mode:'edit'}),stop:async()=>{},save:()=>new Promise(resolve=>resolveSave=resolve),approve:()=>{},navigate:async()=>events.push('left')});await flow.request('/games');const first=flow.saveAndLeave();await assert.rejects(flow.saveAndLeave(),/Wait/);assert.equal(flow.cancel(),false);resolveSave();await first;assert.deepEqual(events,['left']);});
test('save is not called without a pending destination',async()=>{const {flow}=fixture();await assert.rejects(flow.saveAndLeave(),/destination/);});
