import test from 'node:test';
import assert from 'node:assert/strict';
import {createEditorMcpClient,editObjectOperations} from '../engine/editor/mcp-client.mjs';
function fixture(){
 let project={id:'project',name:'World',settings:{},entities:[],assets:[]},state={mode:'edit',busy:false},batch=[],applies=0,undos=0;const sent=[],logs=[];
 const editor={getProject:()=>structuredClone(project),previewWorld:async()=>({previewId:'preview-1',summary:{entityCount:1},entities:[]}),applyWorld:async()=>{applies++;},undo:async()=>{undos++;}};
 const client=createEditorMcpClient({getEditor:()=>editor,getState:()=>state,autoPoll:false,now:()=>100, onLog:entry=>logs.push(entry),fetchFn:async(url,options)=>{const body=options.body?JSON.parse(options.body):undefined;sent.push({url,body});if(url.endsWith('/connect'))return Response.json({sessionId:'session',projectId:project.id,allowWrites:body.allowWrites,protocol:1});if(url.endsWith('/commands'))return Response.json({sessionId:'session',projectId:'project',commands:batch.splice(0,1)});return Response.json({ok:true});}});
 return {client,sent,logs,setProject:id=>{project.id=id;},setState:value=>{state=value;},counts:()=>({applies,undos}),queue:(command,args={},extra={})=>batch.push({id:'cmd-'+(sent.length+batch.length),command,arguments:args,projectId:'project',expiresAt:200,...extra}),connect:allowWrites=>client.connect('x'.repeat(48),{allowWrites})};
}
test('MCP client is disconnected by default and rejects malformed tokens',async()=>{const f=fixture();assert.equal(f.client.state.connected,false);await assert.rejects(f.client.connect('short'));assert.equal(f.sent.length,0);});
test('read-only connection inspects a bounded project without enabling writes',async()=>{const f=fixture();await f.connect(false);f.queue('get_scene');await f.client.pollOnce();assert.equal(f.sent.at(-1).body.result.projectId,'project');f.queue('undo');await f.client.pollOnce();assert.equal(f.sent.at(-1).body.error.code,'EDITOR_REJECTED');assert.equal(f.counts().undos,0);});
test('apply requires both explicit write grant and a preview from this session',async()=>{const f=fixture();await f.connect(true);f.queue('apply_world',{previewId:'missing'});await f.client.pollOnce();assert.equal(f.counts().applies,0);f.queue('preview_world',{recipe:{}});await f.client.pollOnce();f.queue('apply_world',{previewId:'preview-1'});await f.client.pollOnce();assert.equal(f.counts().applies,1);f.queue('apply_world',{previewId:'preview-1'});await f.client.pollOnce();assert.equal(f.counts().applies,1);});
test('expired and duplicate commands never mutate',async()=>{const f=fixture();await f.connect(true);f.queue('undo',{}, {id:'same',expiresAt:99});await f.client.pollOnce();assert.equal(f.counts().undos,0);f.queue('undo',{}, {id:'same'});await f.client.pollOnce();f.queue('undo',{}, {id:'same'});await f.client.pollOnce();assert.equal(f.counts().undos,1);});
test('Play and busy editor reject MCP commands',async()=>{const f=fixture();await f.connect(true);f.setState({mode:'play',busy:false});f.queue('undo');await f.client.pollOnce();f.setState({mode:'edit',busy:true});f.queue('preview_world',{recipe:{}});await f.client.pollOnce();assert.deepEqual(f.counts(),{applies:0,undos:0});assert.equal(f.sent.at(-1).body.error.code,'EDITOR_REJECTED');});
test('changing project disconnects before processing a queued write',async()=>{const f=fixture();await f.connect(true);f.queue('undo');f.setProject('other');await f.client.pollOnce();assert.equal(f.client.state.connected,false);assert.equal(f.counts().undos,0);});
test('disconnect clears local permissions and previews',async()=>{const f=fixture();await f.connect(true);await f.client.disconnect();assert.deepEqual(f.client.state,{connected:false,allowWrites:false});assert.match(f.sent.at(-1).url,/disconnect$/);});
test('unknown commands are rejected and raw errors never leave browser',async()=>{const f=fixture();await f.connect(true);f.queue('execute_python',{code:'bad'});await f.client.pollOnce();assert.deepEqual(f.sent.at(-1).body.error,{code:'EDITOR_REJECTED'});assert.deepEqual(f.counts(),{applies:0,undos:0});});
test('edit and settings commands require the write grant',async()=>{const f=fixture();await f.connect(false);f.queue('edit_objects',{operations:[{op:'remove',id:'a'}]});await f.client.pollOnce();assert.equal(f.sent.at(-1).body.error.code,'EDITOR_REJECTED');f.queue('set_level_settings',{settings:{lives:3}});await f.client.pollOnce();assert.equal(f.sent.at(-1).body.error.code,'EDITOR_REJECTED');});
test('object edits merge material and light and remove null components',()=>{
 const project={entities:[{id:'lift',material:{color:'#111111',roughness:.4,metalness:0},light:{color:'#ffffff',intensity:3,distance:30},components:{rigidbody:{type:'static'},mover:{offset:[1,0,0],period:2},hazard:{}}}]};
 const [update,remove]=editObjectOperations(project,[{op:'update',id:'lift',patch:{material:{color:'#ff0000'},light:{intensity:9},components:{mover:{offset:[0,3,0],period:5},hazard:null}}},{op:'remove',id:'lift'}]);
 assert.deepEqual(update.patch.material,{color:'#ff0000',roughness:.4,metalness:0});assert.equal(update.patch.light.intensity,9);assert.equal(update.patch.light.distance,30);
 assert.deepEqual(update.patch.components,{rigidbody:{type:'static'},mover:{offset:[0,3,0],period:5}});assert.deepEqual(remove,{op:'remove',id:'lift'});
 assert.throws(()=>editObjectOperations(project,[{op:'remove',id:'missing'}]),/not in this project/);
});
