import test from 'node:test';
import assert from 'node:assert/strict';
import {createHmac} from 'node:crypto';
import {fixture,actor,call,stamp} from './helpers/stripe-fixture.mjs';
import {handleStripeCommerce} from '../platform/server/stripe-commerce.mjs';
import {verifyStripeEvent,stripeConfiguration} from '../platform/server/stripe-client.mjs';
const rejects=status=>e=>e.status===status;
async function setup(t,mode='test',creator=true){const f=await fixture(mode,creator);t.after(()=>f.sql.close());const saved=globalThis.fetch;t.after(()=>globalThis.fetch=saved);f.calls=[];f.refunded=0;f.disputed=false;f.completed=false;f.ready=true;
 globalThis.fetch=async(url,opts={})=>{assert.ok(url.startsWith('https://api.stripe.com/v1/'));f.calls.push({url,...opts});
 if(url.includes('/accounts/'))return Response.json({id:'acct_fixture',country:'US',charges_enabled:f.ready,payouts_enabled:f.ready});
 if(url.includes('/checkout/sessions')&&opts.method==='POST'){const b=new URLSearchParams(opts.body);f.orderId=b.get('metadata[crate_order]');f.checkoutFields=b;assert.ok(Number(b.get('expires_at'))>=stamp()+1800);return Response.json({id:'cs_'+mode+'_fixture',livemode:mode==='live',url:'https://checkout.stripe.com/fixture'});}
 const charge={id:'ch_fixture',created:stamp(),livemode:mode==='live',currency:'usd',amount:999,payment_intent:'pi_fixture',paid:true,captured:true,amount_refunded:f.refunded,disputed:f.disputed,metadata:{crate_app:'crateshipgames',crate_order:f.orderId},balance_transaction:{fee:59,currency:'usd'}};
 if(url.includes('/charges/'))return Response.json(charge);
 if(url.includes('/checkout/sessions/'))return Response.json({id:'cs_'+mode+'_fixture',livemode:mode==='live',metadata:{crate_order:f.orderId,crate_app:'crateshipgames'},client_reference_id:f.orderId,mode:'payment',amount_total:f.badAmount?1:999,currency:'usd',status:f.expired?'expired':f.completed?'complete':'open',payment_status:f.completed?'paid':'unpaid',payment_intent:{id:'pi_fixture',status:'succeeded',metadata:{crate_order:f.orderId,crate_app:'crateshipgames'},currency:'usd',amount_received:999,...(creator?{transfer_data:{destination:'acct_fixture'},application_fee_amount:200}:{}),latest_charge:charge}});
 throw new Error('Unexpected provider request '+url);
 };return f;}
const buy=f=>call(f,'/checkout',f.buyer,'POST',{gameId:f.gameId,requestKey:crypto.randomUUID(),priceMinor:1});
const count=(f,table)=>f.sql.prepare('SELECT COUNT(*) n FROM '+table).get().n;
function eventRequest(f,event,change={}){const body=JSON.stringify({id:'evt_fixture',type:'checkout.session.completed',livemode:f.env.STRIPE_MODE==='live',data:{object:{id:'cs_'+f.env.STRIPE_MODE+'_fixture',metadata:{crate_app:'crateshipgames'}}},...event}),at=stamp(),sig=createHmac('sha256',f.env.STRIPE_WEBHOOK_SECRET).update(at+'.'+body).digest('hex');return new Request(f.env.APP_ORIGIN+'/api/platform/stripe/webhook',{method:'POST',headers:{'stripe-signature':`t=${at},v1=${sig}`,...change},body});}
const webhook=(f,event)=>handleStripeCommerce(eventRequest(f,event),f.env,'/stripe/webhook');
test('live readiness requires explicit verified configuration',()=>{assert.equal(stripeConfiguration({STRIPE_MODE:'live',STRIPE_SECRET_KEY:'sk_test_fixture'}).configured,false);assert.equal(stripeConfiguration({STRIPE_MODE:'live',STRIPE_SECRET_KEY:'sk_live_fixture',STRIPE_LIVE_APPROVED:'true',COMMERCE_POLICY_VERSION:'draft-v1',STRIPE_WEBHOOK_SECRET:'whsec_fixture'}).live,false);});
test('server price, split and concurrent checkout requests remain one order',async t=>{const f=await setup(t);const values=await Promise.all([buy(f),buy(f)]);assert.equal(values.length,2);assert.equal(count(f,'platform_stripe_orders'),1);assert.equal(f.checkoutFields.get('line_items[0][price_data][unit_amount]'),'999');assert.equal(f.checkoutFields.get('payment_intent_data[application_fee_amount]'),'200');assert.equal(f.sql.prepare('SELECT creator_minor FROM platform_stripe_orders').get().creator_minor,799);assert.ok(f.calls.filter(c=>c.method==='POST').every(c=>c.headers['Idempotency-Key']==='crate-order-'+f.orderId));});
test('sandbox payment cannot grant live purchases, licenses or revenue',async t=>{const f=await setup(t);await buy(f);f.completed=true;await webhook(f);assert.equal(f.sql.prepare('SELECT status FROM platform_stripe_orders').get().status,'paid');for(const table of ['platform_purchases','platform_licenses','platform_library','platform_revenue_events'])assert.equal(count(f,table),0);});
test('verified mocked live payment grants once and platform alone pays processing fee',async t=>{const f=await setup(t,'live');await buy(f);f.completed=true;await webhook(f);await webhook(f);await webhook(f,{id:'evt_other'});assert.equal(count(f,'platform_licenses'),1);assert.equal(count(f,'platform_purchases'),1);assert.equal(count(f,'platform_revenue_events'),1);assert.equal(count(f,'platform_creator_obligations'),1);const r=f.sql.prepare('SELECT * FROM platform_revenue_events').get();assert.equal(r.creator_minor,799);assert.equal(r.platform_minor,200);assert.equal(f.sql.prepare('SELECT platform_delta_minor FROM platform_revenue_adjustments').get().platform_delta_minor,-59);});
test('platform owned checkout has no seller transfer or application fee',async t=>{const f=await setup(t,'live',false);await buy(f);assert.equal(f.checkoutFields.get('payment_intent_data[transfer_data][destination]'),null);f.completed=true;await webhook(f);assert.equal(f.sql.prepare('SELECT platform_minor FROM platform_revenue_events').get().platform_minor,999);assert.equal(count(f,'platform_creator_obligations'),0);});
test('duplicate and increasing partial refunds revoke access and do not overcount',async t=>{const f=await setup(t,'live');await buy(f);f.completed=true;await webhook(f);f.refunded=300;await webhook(f,{id:'evt_refund1',type:'charge.refunded',data:{object:{id:'ch_fixture'}}});await webhook(f,{id:'evt_refund2',type:'charge.refunded',data:{object:{id:'ch_fixture'}}});f.refunded=999;await webhook(f,{id:'evt_refund3',type:'charge.refunded',data:{object:{id:'ch_fixture'}}});assert.equal(f.sql.prepare('SELECT status FROM platform_licenses').get().status,'revoked');assert.equal(count(f,'platform_library'),0);assert.equal(f.sql.prepare("SELECT SUM(creator_delta_minor+platform_delta_minor) total FROM platform_revenue_adjustments WHERE reason='Stripe sale refund'").get().total,-999);assert.equal(f.sql.prepare('SELECT refunded_minor FROM platform_stripe_orders').get().refunded_minor,999);});
test('refund arriving before completion records sale and refund without active license',async t=>{const f=await setup(t,'live');await buy(f);f.completed=true;f.refunded=999;await webhook(f,{type:'charge.refunded',data:{object:{id:'ch_fixture'}}});assert.equal(count(f,'platform_revenue_events'),1);assert.equal(count(f,'platform_licenses'),0);assert.equal(f.sql.prepare('SELECT status FROM platform_purchases').get().status,'refunded');});
test('dispute revokes game access and holds creator obligation',async t=>{const f=await setup(t,'live');await buy(f);f.completed=true;await webhook(f);f.disputed=true;await webhook(f,{id:'evt_dispute',type:'charge.dispute.created',data:{object:{charge:'ch_fixture'}}});assert.equal(f.sql.prepare('SELECT status FROM platform_licenses').get().status,'revoked');assert.equal(f.sql.prepare('SELECT status FROM platform_creator_obligations').get().status,'held');});
test('wrong totals and unsigned or mismatched-mode events fail without granting licenses',async t=>{const f=await setup(t,'live');await buy(f);f.completed=true;f.badAmount=true;await assert.rejects(webhook(f),rejects(409));assert.equal(count(f,'platform_licenses'),0);await assert.rejects(verifyStripeEvent(eventRequest(f,{}, {'stripe-signature':'t=1,v1='+'0'.repeat(64)}),f.env),rejects(400));await assert.rejects(verifyStripeEvent(eventRequest(f,{livemode:false}),f.env),rejects(400));});
test('foreign application checkouts never fetch payment or grant access',async t=>{const f=await setup(t,'live');await webhook(f,{data:{object:{id:'cs_other',metadata:{crate_app:'other-app'}}}});assert.equal(f.calls.length,0);assert.equal(count(f,'platform_licenses'),0);});
test('pending checkout and expired checkout cannot grant ownership',async t=>{const f=await setup(t,'live');await buy(f);await webhook(f);assert.equal(count(f,'platform_licenses'),0);f.expired=true;await webhook(f,{id:'evt_expired',type:'checkout.session.expired'});assert.equal(f.sql.prepare('SELECT status FROM platform_stripe_orders').get().status,'expired');});
test('incomplete seller, missing acceptance and disabled payments block new charges',async t=>{const f=await setup(t,'live');f.ready=false;await assert.rejects(buy(f),rejects(409));f.ready=true;f.sql.exec('DELETE FROM platform_seller_acceptances');await assert.rejects(buy(f),rejects(409));f.sql.exec("UPDATE platform_feature_flags SET enabled=0 WHERE key='PAYMENTS_ENABLED'");await assert.rejects(buy(f),rejects(503));assert.equal(count(f,'platform_stripe_orders'),0);});
test('sandbox requires owner MFA and order status cannot leak to another buyer',async t=>{const f=await setup(t);const player=await actor(f,'PLAYER');await assert.rejects(call(f,'/checkout',player,'POST',{gameId:f.gameId,requestKey:crypto.randomUUID()}),rejects(403));const noMfa=await actor(f,'OWNER',false);await assert.rejects(call(f,'/checkout',noMfa,'POST',{gameId:f.gameId,requestKey:crypto.randomUUID()}),rejects(403));await buy(f);const other=await actor(f);await assert.rejects(call(f,'/checkout/orders/'+f.orderId,other),rejects(404));});
test('approved pricing cannot be changed after review',async t=>{const f=await setup(t,'live');f.sql.exec("UPDATE platform_games SET status='approved'");await assert.rejects(call(f,'/developer/games/'+f.gameId+'/pricing',f.seller,'PUT',{priceMinor:599}),rejects(409));});
test('tampered signed payload and cross origin checkout are rejected',async t=>{const f=await setup(t);const signed=eventRequest(f),headers=signed.headers;await assert.rejects(verifyStripeEvent(new Request(signed.url,{method:'POST',headers,body:'{"tampered":true}'}),f.env),rejects(400));await assert.rejects(handleStripeCommerce(new Request(f.env.APP_ORIGIN+'/api/platform/checkout',{method:'POST',headers:{origin:'https://foreign.test',cookie:f.buyer.cookie,'content-type':'application/json'},body:JSON.stringify({gameId:f.gameId,requestKey:crypto.randomUUID()})}),f.env,'/checkout'),rejects(403));assert.equal(count(f,'platform_stripe_orders'),0);});
test('provider connection failure preserves one retryable order and old unsent order expires',async t=>{const f=await setup(t,'test',false),provider=globalThis.fetch;globalThis.fetch=async()=>{throw new Error('Network unavailable');};await assert.rejects(buy(f),rejects(503));assert.equal(count(f,'platform_stripe_orders'),1);globalThis.fetch=provider;await buy(f);assert.equal(count(f,'platform_stripe_orders'),1);f.sql.prepare("UPDATE platform_stripe_orders SET session_id=NULL,status='creating',created_at=?").run(stamp()-1900);await assert.rejects(buy(f),rejects(409));assert.equal(f.sql.prepare('SELECT status FROM platform_stripe_orders').get().status,'expired');});
