[package]
name = "koko-render"
version.workspace = true
edition.workspace = true

[dependencies]
koko-core = { path = "../koko-core" }
wgpu = { workspace = true }
winit = { workspace = true }
glam = { workspace = true }
bytemuck = { version = "1", features = ["derive"] }
tracing = { workspace = true }
image = { workspace = true }
pollster = { workspace = true }

# glTF model loading
gltf = { version = "1.4", features = ["utils"] }
