[package]
name = "koko-wasm"
version.workspace = true
edition.workspace = true

[lib]
crate-type = ["cdylib", "rlib"]

[dependencies]
koko-world = { path = "../koko-world" }
koko-commands = { path = "../koko-commands" }
koko-nav = { path = "../koko-nav" }
koko-sim = { path = "../koko-sim" }
serde = { workspace = true }
serde_json = { workspace = true }
wasm-bindgen = "0.2"
serde-wasm-bindgen = "0.6"
