import {HttpError,json,readJson,id,now,database,audit,requireMutationOrigin} from './common.mjs';
import {requireUser,requireRole} from './identity.mjs';
import {validateTerms} from './commerce.mjs';

export const DISABLED_PROVIDER_FLAGS = new Set(['PAYMENTS_ENABLED','STRIPE_ENABLED','GOOGLE_ADS_ENABLED','H5_GAME_ADS_ENABLED','REWARDED_ADS_ENABLED','INTERSTITIAL_ADS_ENABLED','CREATOR_PAYOUTS_ENABLED','PREMIUM_SALES_ENABLED']);
// Flags with no server workflow behind them yet; enabling them would signal a feature that does not exist.
export const UNIMPLEMENTED_FLAGS = new Set(['ENGINE_PUBLISHING_ENABLED','PREMIUM_DOWNLOADS_ENABLED']);
export const LIMITS=Object.freeze({uploadBytes:500*1024*1024,partBytes:8*1024*1024,projectBytes:2*1024*1024,progressBytes:64*1024,files:10000,extractedBytes:2*1024*1024*1024,compressionRatio:100});
const DEVELOPER_ROLES=['DEVELOPER','PARTNER_DEVELOPER','OWNER'];
const REVIEW_ROLES=['OWNER','CONTENT_MANAGER','MODERATOR'];
const parse=(s,fallback={})=>{try{return JSON.parse(s);}catch{return fallback;}};
const rows=async(stmt)=>(await stmt.all()).results||[];
const text=(value,max=200)=>String(value??'').trim().slice(0,max);
const fail=(status,message,code='INVALID_REQUEST')=>{throw new HttpError(status,message,code);};
export function publicGame(g){if(!g)return null;return {id:g.id,slug:g.slug,title:g.title,description:g.description,shortDescription:g.short_description,kind:g.kind,status:g.status,genres:parse(g.genres_json,[]),tags:parse(g.tags_json,[]),metadata:parse(g.metadata_json),cover:g.cover_url,hero:g.hero_url,featured:Boolean(g.featured),priceMinor:g.price_minor,currency:g.currency,developerId:g.developer_id,versionId:g.active_version_id,createdAt:g.created_at,updatedAt:g.updated_at};}
export async function flags(env){const result={};for(const row of await rows(database(env).prepare('SELECT key,enabled FROM platform_feature_flags')))result[row.key]=Boolean(row.enabled);for(const key of DISABLED_PROVIDER_FLAGS)result[key]=false;return result;}
export async function demandFlag(env,key){if(!(await flags(env))[key])fail(503,'This feature is not open yet.','FEATURE_DISABLED');}
export async function ownGame(env,user,gameId,{readOnly=false}={}){const g=await database(env).prepare('SELECT * FROM platform_games WHERE id=?').bind(gameId).first();if(!g)fail(404,'Game not found.');if(g.developer_id!==user.id){const member=await database(env).prepare("SELECT 1 FROM platform_game_members WHERE game_id=? AND user_id=? AND (permission='edit' OR (?=1 AND permission='analytics'))").bind(gameId,user.id,readOnly?1:0).first();if(!member)fail(403,'You cannot edit this game.','FORBIDDEN');}return g;}
export async function rate(env,userId,action,limit=60,window=60){const db=database(env),bucket=Math.floor(now()/window);const r=await db.prepare('INSERT INTO platform_operation_limits VALUES (?,?,?,1) ON CONFLICT(user_id,action,bucket) DO UPDATE SET count=count+1 RETURNING count').bind(userId,action,bucket).first();if(r.count>limit)fail(429,'Please wait before trying again.','RATE_LIMITED');}
async function verified(request,env){const user=await requireUser(request,env);if(!user.emailVerified)fail(403,'Verify your email to continue.','EMAIL_VERIFICATION_REQUIRED');return user;}
function safeList(value){return Array.isArray(value)?[...new Set(value.map(v=>text(v,36)).filter(Boolean))].slice(0,12):[];}
function gameInput(body){const title=text(body.title,120),slug=text(body.slug||title.toLowerCase().replace(/[^a-z0-9]+/g,'-').replace(/^-|-$/g,''),72);if(title.length<2||!/^[a-z0-9]+(?:-[a-z0-9]+)*$/.test(slug))fail(400,'Enter a title and a valid game slug.');if(!['web','download','both'].includes(body.kind))fail(400,'Choose browser, download, or both.');return {title,slug,kind:body.kind,description:text(body.description,12000),short:text(body.shortDescription,240),genres:JSON.stringify(safeList(body.genres)),tags:JSON.stringify(safeList(body.tags)),metadata:JSON.stringify({controls:text(body.controls,2000),languages:safeList(body.languages),platforms:safeList(body.platforms),contentInformation:text(body.contentInformation,2000),systemRequirements:text(body.systemRequirements,3000)})};}
async function published(db,gameId){const game=await db.prepare("SELECT * FROM platform_games WHERE id=? AND status='published'").bind(gameId).first();if(!game)fail(404,'This game is not available.','GAME_UNAVAILABLE');return game;}
export async function handleData(request,env,path){
 const method=request.method,url=new URL(request.url),db=database(env);
 if(!['GET','HEAD','OPTIONS'].includes(method))requireMutationOrigin(request,env);
 if(path==='/config'&&method==='GET'){const f=await flags(env);return json({flags:f,auth:{email:Boolean(env.AUTH_SECRET&&env.MAIL_FROM&&env.MAIL_API_KEY&&env.MAIL_PROVIDER==='resend'),google:Boolean(env.GOOGLE_CLIENT_ID&&env.GOOGLE_CLIENT_SECRET)},limits:LIMITS,gameOrigin:env.GAME_CONTENT_ORIGIN||null});}
 if(path==='/me'&&method==='GET'){try{return json({user:await requireUser(request,env)});}catch(error){if(error.status===401)return json({user:null});throw error;}}
 if(path==='/catalog'&&method==='GET'){
  const q=text(url.searchParams.get('q'),100),kind=url.searchParams.get('kind'),page=Math.max(1,Math.min(1000,Number(url.searchParams.get('page'))||1));
  const clauses=["status='published'"],params=[];
  if(q){clauses.push("(title LIKE ? ESCAPE '\\' OR short_description LIKE ? ESCAPE '\\' OR genres_json LIKE ? ESCAPE '\\')");const pattern='%'+q.replace(/[\\%_]/g,'\\$&')+'%';params.push(pattern,pattern,pattern);}
  if(kind==='free')clauses.push('(price_minor IS NULL OR price_minor=0)');if(kind==='premium')clauses.push('price_minor>0');
  const where=clauses.join(' AND ');const total=await db.prepare(`SELECT count(*) total FROM platform_games WHERE ${where}`).bind(...params).first();
  const games=await rows(db.prepare(`SELECT * FROM platform_games WHERE ${where} ORDER BY featured DESC,published_at DESC LIMIT 24 OFFSET ?`).bind(...params,(page-1)*24));return json({games:games.map(publicGame),total:total.total,page});
 }
 if(path.startsWith('/catalog/')&&method==='GET'){const game=await db.prepare("SELECT * FROM platform_games WHERE slug=? AND status='published'").bind(decodeURIComponent(path.slice(9))).first();if(!game)fail(404,'Game not found.');return json({game:publicGame(game)});}
 if(path==='/waitlist'&&method==='POST'){await demandFlag(env,'CREATOR_WAITLIST_ENABLED');const user=await verified(request,env);await rate(env,user.id,'waitlist',5,3600);await db.prepare('INSERT OR IGNORE INTO platform_waitlist(id,user_id,email,source,created_at) VALUES(?,?,?,?,?)').bind(id(),user.id,user.email,'creator_hub',now()).run();return json({joined:true});}
 if(path==='/profile'&&method==='PUT'){const user=await requireUser(request,env),body=await readJson(request,4000),username=text(body.username,30),name=text(body.displayName,80);if(!/^[a-zA-Z0-9_]{3,30}$/.test(username)||!name)fail(400,'Use a 3–30 character username with letters, numbers or underscores.');await db.prepare('UPDATE platform_users SET username=?,display_name=?,updated_at=? WHERE id=?').bind(username,name,now(),user.id).run();return json({saved:true});}
 if(path==='/preferences'){
  const user=await requireUser(request,env);if(method==='GET'){const r=await db.prepare('SELECT data_json FROM platform_preferences WHERE user_id=?').bind(user.id).first();return json({preferences:parse(r?.data_json)});}
  if(method==='PUT'){const b=await readJson(request,4000),preferences={reducedMotion:Boolean(b.reducedMotion),language:['en','es'].includes(b.language)?b.language:'en',advertisingConsent:b.advertisingConsent===true,analyticsConsent:b.analyticsConsent===true};await db.prepare('INSERT INTO platform_preferences VALUES(?,?,?) ON CONFLICT(user_id) DO UPDATE SET data_json=excluded.data_json,updated_at=excluded.updated_at').bind(user.id,JSON.stringify(preferences),now()).run();return json({preferences});}
 }
 if(path==='/favorites'||path.startsWith('/favorites/')){
  const user=await requireUser(request,env);if(method==='GET')return json({items:(await rows(db.prepare('SELECT g.* FROM platform_favorites f JOIN platform_games g ON g.id=f.game_id WHERE f.user_id=? ORDER BY f.created_at DESC').bind(user.id))).map(publicGame)});
  const body=method==='POST'?await readJson(request,1000):{},gameId=path.slice(11)||body.gameId;if(!gameId)fail(400,'Choose a game.');
  if(method==='POST'){await published(db,gameId);await db.prepare('INSERT OR IGNORE INTO platform_favorites VALUES(?,?,?)').bind(user.id,gameId,now()).run();return json({saved:true});}
  if(method==='DELETE'){await db.prepare('DELETE FROM platform_favorites WHERE user_id=? AND game_id=?').bind(user.id,gameId).run();return json({saved:true});}
 }
 if(path==='/library'){
  const user=await requireUser(request,env);if(method==='GET')return json({items:(await rows(db.prepare('SELECT g.* FROM platform_library l JOIN platform_games g ON g.id=l.game_id WHERE l.user_id=? ORDER BY l.created_at DESC').bind(user.id))).map(publicGame)});
  if(method==='POST'){const body=await readJson(request,1000),game=await published(db,body.gameId);if(game.price_minor>0)fail(503,'Purchases are not yet enabled.','PAYMENTS_DISABLED');await db.prepare("INSERT OR IGNORE INTO platform_library VALUES(?,?,'free_claim',?)").bind(user.id,game.id,now()).run();return json({saved:true});}
 }
 if(path==='/history'&&method==='GET'){const user=await requireUser(request,env);return json({items:(await rows(db.prepare('SELECT g.*,h.last_played_at,h.play_count FROM platform_play_history h JOIN platform_games g ON g.id=h.game_id WHERE h.user_id=? ORDER BY h.last_played_at DESC LIMIT 24').bind(user.id))).map(g=>({...publicGame(g),lastPlayedAt:g.last_played_at,playCount:g.play_count}))});}
 if(path==='/notifications'&&method==='GET'){const user=await requireUser(request,env);return json({items:await rows(db.prepare('SELECT id,type,title,body,href,created_at createdAt,read_at readAt FROM platform_notifications WHERE user_id=? ORDER BY created_at DESC LIMIT 50').bind(user.id))});}
 if(path.startsWith('/notifications/')&&method==='PATCH'){const user=await requireUser(request,env);await db.prepare('UPDATE platform_notifications SET read_at=? WHERE id=? AND user_id=?').bind(now(),path.slice(15),user.id).run();return json({saved:true});}
 if(path==='/wallet'&&method==='GET'){const user=await requireUser(request,env),balances={points:0,credits:0,tokens:0};for(const row of await rows(db.prepare('SELECT currency,SUM(amount) balance FROM platform_wallet_transactions WHERE user_id=? GROUP BY currency').bind(user.id)))balances[row.currency]=row.balance;return json({balances,transactions:await rows(db.prepare('SELECT id,currency,amount,type,created_at createdAt FROM platform_wallet_transactions WHERE user_id=? ORDER BY created_at DESC LIMIT 50').bind(user.id))});}
 if(path.startsWith('/rewards')||path.startsWith('/ads')||path.startsWith('/checkout')||path.startsWith('/payments')||path.startsWith('/payouts'))fail(503,'This service is not enabled. No transaction has been created.','PROVIDER_DISABLED');
 if(path==='/projects'||path.startsWith('/projects/')){
  const user=await requireUser(request,env),projectId=path.slice(10);if(method==='GET'&&!projectId)return json({projects:await rows(db.prepare('SELECT id,name,revision,created_at createdAt,updated_at updatedAt FROM platform_projects WHERE user_id=? AND deleted_at IS NULL ORDER BY updated_at DESC LIMIT 100').bind(user.id))});
  if(method==='POST'&&!projectId){const b=await readJson(request,LIMITS.projectBytes),name=text(b.name||'Untitled project',120),pid=id(),project=JSON.stringify(b.project||{format:'crate-engine-project',version:3,objects:[]});await rate(env,user.id,'project-create',20,3600);await db.prepare('INSERT INTO platform_projects(id,user_id,name,project_json,created_at,updated_at) VALUES(?,?,?,?,?,?)').bind(pid,user.id,name,project,now(),now()).run();return json({project:{id:pid,name,revision:1}},201);}
  const p=await db.prepare('SELECT * FROM platform_projects WHERE id=? AND user_id=? AND deleted_at IS NULL').bind(projectId,user.id).first();if(!p)fail(404,'Project not found.');
  if(method==='GET')return json({project:{id:p.id,name:p.name,revision:p.revision,data:parse(p.project_json),updatedAt:p.updated_at}});
  if(method==='PUT'){const b=await readJson(request,LIMITS.projectBytes);if(!Number.isInteger(b.revision))fail(400,'A project revision is required.');const result=await db.prepare('UPDATE platform_projects SET name=?,project_json=?,revision=revision+1,updated_at=? WHERE id=? AND user_id=? AND revision=?').bind(text(b.name||p.name,120),JSON.stringify(b.project??parse(p.project_json)),now(),p.id,user.id,b.revision).run();if(!result.meta.changes)fail(409,'This project changed in another session. Reload before saving.','REVISION_CONFLICT');return json({project:{id:p.id,name:text(b.name||p.name,120),revision:b.revision+1}});}
  if(method==='DELETE'){await db.prepare('UPDATE platform_projects SET deleted_at=? WHERE id=? AND user_id=?').bind(now(),p.id,user.id).run();return json({deleted:true});}
 }
 if(path==='/developer/games'||/^\/developer\/games\/[^/]+$/.test(path)){
  const user=await requireRole(request,env,DEVELOPER_ROLES),gameId=path.slice(17);
  if(method==='GET'&&!gameId)return json({games:(await rows(db.prepare('SELECT DISTINCT g.* FROM platform_games g LEFT JOIN platform_game_members m ON m.game_id=g.id WHERE g.developer_id=? OR m.user_id=? ORDER BY g.updated_at DESC').bind(user.id,user.id))).map(publicGame)});
  if(method==='POST'&&!gameId){if(!user.emailVerified)fail(403,'Verify your email first.');await rate(env,user.id,'game-create',20,3600);const v=gameInput(await readJson(request,20000)),gid=id();await db.batch([db.prepare('INSERT INTO platform_games(id,slug,developer_id,title,description,short_description,kind,genres_json,tags_json,metadata_json,created_at,updated_at) VALUES(?,?,?,?,?,?,?,?,?,?,?,?)').bind(gid,v.slug,user.id,v.title,v.description,v.short,v.kind,v.genres,v.tags,v.metadata,now(),now()),db.prepare('INSERT INTO platform_audit(id,actor_id,action,target_id,detail_json,result,created_at) VALUES(?,?,?,?,?,?,?)').bind(id(),user.id,'game.create',gid,'{}','success',now())]);return json({game:publicGame(await ownGame(env,user,gid))},201);}
  const game=await ownGame(env,user,gameId,{readOnly:method==='GET'});if(method==='GET')return json({game:publicGame(game),canEdit:game.developer_id===user.id||Boolean(await db.prepare("SELECT 1 FROM platform_game_members WHERE game_id=? AND user_id=? AND permission='edit'").bind(game.id,user.id).first()),versions:await rows(db.prepare('SELECT * FROM platform_game_versions WHERE game_id=? ORDER BY created_at DESC').bind(game.id))});
  if(method==='PUT'){if(['submitted','under_review','approved','published'].includes(game.status))fail(409,'Create a new version or request a listing review before editing.');const v=gameInput(await readJson(request,20000));const result=await db.prepare('UPDATE platform_games SET title=?,description=?,short_description=?,genres_json=?,tags_json=?,metadata_json=?,updated_at=? WHERE id=? AND status=?').bind(v.title,v.description,v.short,v.genres,v.tags,v.metadata,now(),game.id,game.status).run();if(!result.meta.changes)fail(409,'The listing review state changed. Reload before editing.');return json({game:publicGame(await ownGame(env,user,game.id))});}
 }
 const submit=/^\/developer\/games\/([^/]+)\/submit$/.exec(path);
 if(submit&&method==='POST'){const user=await requireRole(request,env,DEVELOPER_ROLES),game=await ownGame(env,user,submit[1]),b=await readJson(request,3000);if(b.rightsConfirmed!==true)fail(400,'Confirm distribution rights before submitting.');const version=await db.prepare("SELECT * FROM platform_game_versions WHERE id=? AND game_id=? AND status='ready' AND scan_status='clean'").bind(b.versionId,game.id).first();if(!version)fail(409,'A validated and clean scanned build is required.');await db.batch([db.prepare("UPDATE platform_games SET status='submitted',active_version_id=?,updated_at=? WHERE id=?").bind(version.id,now(),game.id),db.prepare('INSERT OR IGNORE INTO platform_rights_declarations VALUES(?,?,?,?,?,?)').bind(id(),game.id,version.id,user.id,'2026-09-27',now())]);await audit(env,{actor:user.id,action:'game.submit',target:game.id,detail:{versionId:version.id}});return json({submitted:true});}
 if(path==='/developer/analytics'&&method==='GET'){const u=await requireRole(request,env,DEVELOPER_ROLES);return json({games:await rows(db.prepare('SELECT g.id,g.title,COUNT(s.id) sessions FROM platform_games g LEFT JOIN platform_game_sessions s ON s.game_id=g.id WHERE g.developer_id=? OR EXISTS(SELECT 1 FROM platform_game_members m WHERE m.game_id=g.id AND m.user_id=?) GROUP BY g.id').bind(u.id,u.id)),earnings:await rows(db.prepare('SELECT currency,status,SUM(amount_minor) amountMinor FROM platform_creator_obligations WHERE creator_id=? GROUP BY currency,status').bind(u.id))});}
 if(path.startsWith('/owner/'))return handleOwner(request,env,path);
 if(path==='/reports'&&method==='POST'){const u=await requireUser(request,env),b=await readJson(request,3000);await published(db,b.gameId);await rate(env,u.id,'report',10,3600);if(!['broken','malware','copyright','content','advertising','technical','other'].includes(b.category))fail(400,'Choose a report category.');await db.prepare('INSERT INTO platform_reports VALUES(?,?,?,?,?,?,?)').bind(id(),b.gameId,u.id,b.category,text(b.detail,2000),'open',now()).run();return json({submitted:true},201);}
 return null;
}

async function handleOwner(request,env,path){
 const u=await requireRole(request,env,['OWNER'],{mfa:true,recent:request.method!=='GET'}),db=database(env),method=request.method;
 if(path==='/owner/overview'&&method==='GET'){
  const count=await db.prepare("SELECT (SELECT COUNT(*) FROM platform_users WHERE status='active') players,(SELECT COUNT(*) FROM platform_games WHERE status='published') games,(SELECT COUNT(*) FROM platform_games WHERE status='submitted') awaitingReview,(SELECT COUNT(*) FROM platform_uploads WHERE status='quarantined') quarantinedUploads,(SELECT COUNT(*) FROM platform_projects WHERE deleted_at IS NULL) projects").first();
  return json({...count,revenue:await rows(db.prepare('SELECT currency,status,SUM(gross_minor) grossMinor,SUM(creator_minor) creatorMinor,SUM(platform_minor) platformMinor FROM platform_revenue_events GROUP BY currency,status')),obligations:await rows(db.prepare('SELECT currency,status,SUM(amount_minor) amountMinor FROM platform_creator_obligations GROUP BY currency,status')),providerReporting:{available:false},flags:await flags(env)});
 }
 if(path==='/owner/games'&&method==='GET')return json({games:(await rows(db.prepare('SELECT * FROM platform_games ORDER BY updated_at DESC LIMIT 100'))).map(publicGame)});
 if(path==='/owner/audit'&&method==='GET')return json({items:await rows(db.prepare('SELECT * FROM platform_audit ORDER BY created_at DESC LIMIT 100'))});
 if(path==='/owner/players'&&method==='GET')return json({items:await rows(db.prepare('SELECT id,username,display_name displayName,status,created_at createdAt,last_login_at lastLoginAt FROM platform_users ORDER BY created_at DESC LIMIT 100'))});
 if(path==='/owner/creators'&&method==='GET')return json({items:await rows(db.prepare("SELECT u.id,u.username,u.display_name displayName,u.status,COUNT(g.id) games FROM platform_users u JOIN platform_user_roles r ON r.user_id=u.id AND r.role IN ('DEVELOPER','PARTNER_DEVELOPER') LEFT JOIN platform_games g ON g.developer_id=u.id GROUP BY u.id LIMIT 100"))});
 if(path==='/owner/flags'&&method==='GET')return json({flags:await flags(env)});
 if(path==='/owner/flags'&&method==='PUT'){const b=await readJson(request,3000);if(typeof b.enabled!=='boolean'||!Object.hasOwn(await flags(env),b.key))fail(400,'Unknown feature flag.');if(b.enabled&&DISABLED_PROVIDER_FLAGS.has(b.key))fail(409,'Provider activation is blocked until readiness and owner go-live approval.','RELEASE_GATE');if(b.enabled&&UNIMPLEMENTED_FLAGS.has(b.key))fail(409,'This feature has no server workflow yet and cannot be enabled.','NOT_IMPLEMENTED');if(b.enabled&&['PUBLIC_CREATOR_UPLOADS_ENABLED','PUBLIC_CREATOR_PUBLISHING_ENABLED'].includes(b.key)&&(!env.GAME_SCANNER||!env.GAME_CONTENT_ORIGIN||!env.PLATFORM_UPLOADS))fail(409,'Storage, scanning and game isolation must be configured first.');if(!text(b.reason,500))fail(400,'A reason is required.');await db.batch([db.prepare('UPDATE platform_feature_flags SET enabled=?,updated_at=?,updated_by=? WHERE key=?').bind(b.enabled?1:0,now(),u.id,b.key),db.prepare('INSERT INTO platform_audit VALUES(?,?,?,?,?,?,?)').bind(id(),u.id,'flag.change',b.key,JSON.stringify({enabled:b.enabled,reason:text(b.reason,500)}),'success',now())]);return json({flags:await flags(env)});}
 if(path==='/owner/agreements'&&method==='GET')return json({items:await rows(db.prepare('SELECT a.*,v.id versionId,v.version,v.terms_json,v.effective_at,v.end_at,v.public_notes FROM platform_agreements a JOIN platform_agreement_versions v ON v.agreement_id=a.id ORDER BY a.created_at DESC,v.version DESC LIMIT 100'))});
 if(path==='/owner/agreements'&&method==='POST'){const b=await readJson(request,15000);if(!['platform_owned','creator_revenue_share','custom'].includes(b.type))fail(400,'Choose a monetization classification.');let terms;try{terms=validateTerms(b.terms,b.type);}catch(e){fail(400,e.message);}if(b.type!=='platform_owned'&&!b.creatorId)fail(400,'A creator must be assigned.');const effective=Number(b.effectiveAt);if(!Number.isSafeInteger(effective)||effective<now())fail(400,'An agreement must start now or in the future.');const aid=id(),vid=id();await db.batch([db.prepare('INSERT INTO platform_agreements VALUES(?,?,?,?,?,?)').bind(aid,text(b.name,120),b.type,b.creatorId||null,u.id,now()),db.prepare('INSERT INTO platform_agreement_versions(id,agreement_id,version,terms_json,minimum_payout_minor,currency,payment_schedule,public_notes,internal_notes,effective_at,end_at,created_by,created_at) VALUES(?,?,?,?,?,?,?,?,?,?,?,?,?)').bind(vid,aid,1,JSON.stringify(terms),Number.isSafeInteger(b.minimumPayoutMinor)?b.minimumPayoutMinor:0,/^[A-Z]{3}$/.test(b.currency)?b.currency:'USD',text(b.paymentSchedule||'not_active',100),text(b.publicNotes,2000),text(b.internalNotes,4000),effective,b.endAt||null,u.id,now()),db.prepare('INSERT INTO platform_audit VALUES(?,?,?,?,?,?,?)').bind(id(),u.id,'agreement.create',aid,JSON.stringify({versionId:vid,type:b.type}),'success',now())]);return json({agreement:{id:aid,versionId:vid,version:1}},201);}
 if(path==='/owner/agreements/assign'&&method==='POST'){const b=await readJson(request,3000),v=await db.prepare('SELECT v.*,a.creator_id FROM platform_agreement_versions v JOIN platform_agreements a ON a.id=v.agreement_id WHERE v.id=?').bind(b.versionId).first(),g=await db.prepare('SELECT * FROM platform_games WHERE id=?').bind(b.gameId).first();if(!v||!g)fail(404,'Agreement version or game not found.');if(v.creator_id&&v.creator_id!==g.developer_id)fail(409,'The agreement creator must match the game developer.');const start=Number(b.effectiveAt);if(!Number.isSafeInteger(start)||start<now()||start<v.effective_at||(v.end_at&&start>=v.end_at))fail(400,'Invalid agreement start.');await db.prepare('INSERT INTO platform_game_agreements VALUES(?,?,?,?,?,?,?)').bind(id(),g.id,v.id,start,b.endAt||v.end_at||null,u.id,now()).run();await audit(env,{actor:u.id,action:'agreement.assign',target:g.id,detail:{versionId:v.id,effectiveAt:start}});return json({assigned:true});}
 const review=/^\/owner\/games\/([^/]+)\/review$/.exec(path);
 if(review&&method==='POST'){const b=await readJson(request,3000),g=await db.prepare('SELECT * FROM platform_games WHERE id=?').bind(review[1]).first();if(!g)fail(404,'Game not found.');if(g.developer_id===u.id)fail(403,'A separate reviewer must review this submission.','SELF_APPROVAL_DENIED');if(!['approve','changes_requested','reject','suspend'].includes(b.decision)||!text(b.reason,1500))fail(400,'A decision and review reason are required.');if(b.decision==='approve'){const v=await db.prepare("SELECT 1 FROM platform_game_versions WHERE id=? AND scan_status='clean' AND status='ready'").bind(g.active_version_id).first();if(!v||!['submitted','under_review'].includes(g.status))fail(409,'A submitted, fully scanned build is required.');}const status={approve:'approved',changes_requested:'changes_requested',reject:'rejected',suspend:'suspended'}[b.decision];await db.batch([db.prepare('UPDATE platform_games SET status=?,updated_at=? WHERE id=?').bind(status,now(),g.id),db.prepare('INSERT INTO platform_reviews VALUES(?,?,?,?,?,?,?)').bind(id(),g.id,g.active_version_id,u.id,b.decision,text(b.reason,1500),now()),db.prepare('INSERT INTO platform_audit VALUES(?,?,?,?,?,?,?)').bind(id(),u.id,'game.review',g.id,JSON.stringify({decision:b.decision,reason:text(b.reason,1500)}),'success',now())]);return json({status});}
 if(['/owner/commerce','/owner/revenue','/owner/payouts','/owner/ads','/owner/sales'].includes(path)&&method==='GET')return json({items:await rows(db.prepare('SELECT id,game_id,creator_id,type,currency,gross_minor,fees_minor,creator_minor,platform_minor,status,occurred_at FROM platform_revenue_events ORDER BY occurred_at DESC LIMIT 100')),enabled:false,message:'Live provider collection and payouts are disabled.'});
 if(['/owner/infrastructure','/owner/storage'].includes(path)&&method==='GET'){const storage=await db.prepare("SELECT COALESCE(SUM(size_bytes),0) bytes,COUNT(*) uploads FROM platform_uploads WHERE status!='aborted'").first();return json({internalEstimate:storage,providerBilling:{available:false},thresholds:await rows(db.prepare('SELECT * FROM platform_usage_thresholds'))});}
 if(path==='/owner/security'&&method==='GET')return json({items:await rows(db.prepare("SELECT * FROM platform_audit WHERE result!='success' OR action LIKE 'auth.%' ORDER BY created_at DESC LIMIT 100"))});
 return null;
}
