import { HttpError, json, id, now, database, requireMutationOrigin } from './common.mjs';
import { requireUser } from './identity.mjs';
import { rate } from './data.mjs';
import { inspectGLB, hashBytes, MAX_MODEL_BYTES } from '../../engine/core/gltf.mjs';

const fail = (status, message, code = 'INVALID_REQUEST') => { throw new HttpError(status, message, code); };
const publicAsset = row => ({ id: row.id, name: row.name, size: row.size, sha256: row.sha256 });
function storage(env) {
  if (!env.ENGINE_ASSETS?.get || !env.ENGINE_ASSETS?.put || !env.ENGINE_ASSETS?.delete) {
    fail(503, 'Private model storage is not configured. Keep a local project export until it is available.', 'ENGINE_ASSET_STORAGE_UNAVAILABLE');
  }
  return env.ENGINE_ASSETS;
}
function bound(env, key, fallback, max) {
  if (env[key] === undefined || env[key] === '') return fallback;
  const value = Number(env[key]);
  if (!Number.isSafeInteger(value) || value < 1 || value > max) fail(503, 'Private model storage limits are not configured correctly.', 'ENGINE_ASSET_CONFIG_INVALID');
  return value;
}
function assetName(request) {
  let name;
  try {
    const encoded = request.headers.get('x-asset-name');
    if (!encoded || encoded.length > 1080) throw new Error();
    name = decodeURIComponent(encoded).trim();
  } catch { fail(400, 'Send an encoded model name in X-Asset-Name.', 'ENGINE_ASSET_NAME_INVALID'); }
  if (!name || name.length > 120 || /[\u0000-\u001f\u007f\\/:<>]/.test(name)) fail(400, 'Use a model name of 1–120 characters without path separators.', 'ENGINE_ASSET_NAME_INVALID');
  return name;
}
async function readBytes(request) {
  if (!/^model\/gltf-binary(?:\s*;|$)/i.test(request.headers.get('content-type') || '')) fail(415, 'Upload a binary GLB file.', 'ENGINE_ASSET_TYPE_INVALID');
  if (Number(request.headers.get('content-length') || 0) > MAX_MODEL_BYTES) fail(413, 'Model files must be at most 32 MiB.', 'ENGINE_ASSET_TOO_LARGE');
  const reader = request.body?.getReader();
  if (!reader) fail(400, 'Upload a GLB file body.', 'ENGINE_ASSET_BODY_REQUIRED');
  const chunks = []; let size = 0;
  try {
    while (true) {
      const { value, done } = await reader.read(); if (done) break;
      size += value.byteLength;
      if (size > MAX_MODEL_BYTES) { await reader.cancel(); fail(413, 'Model files must be at most 32 MiB.', 'ENGINE_ASSET_TOO_LARGE'); }
      chunks.push(value);
    }
  } finally { reader.releaseLock(); }
  const bytes = new Uint8Array(size); let offset = 0;
  for (const chunk of chunks) { bytes.set(chunk, offset); offset += chunk.byteLength; }
  try { inspectGLB(bytes); }
  catch { fail(400, 'Choose a valid GLB 2.0 file with embedded textures and buffers within the complexity limit.', 'ENGINE_ASSET_INVALID_GLB'); }
  return bytes;
}

/** Include these in identity's trusted D1 transaction. Physical deletion is queued. */
export function engineAssetErasureStatements(env, userId) {
  const db = database(env), stamp = now();
  return [db.prepare(`INSERT OR IGNORE INTO platform_engine_asset_purge_queue(id,user_id,storage_key,created_at,not_before)
    SELECT id,user_id,storage_key,?,? FROM platform_engine_assets WHERE user_id=?`).bind(stamp, stamp + 900, userId),
    db.prepare('DELETE FROM platform_engine_assets WHERE user_id=?').bind(userId)];
}

/** Trusted scheduler only, deliberately no public HTTP route. Idempotent R2 delete. */
export async function purgeEngineAssets(env, { limit = 20 } = {}) {
  if (!Number.isSafeInteger(limit) || limit < 1 || limit > 100) fail(400, 'Purge batch size must be 1–100.');
  const bucket = storage(env), db = database(env);
  // Requests cannot remain active for a day on the deployment runtime. Retain
  // keys from abandoned reservations before releasing the account quota.
  const stale=await db.prepare("SELECT id,user_id,storage_key FROM platform_engine_assets WHERE status='pending' AND created_at<? ORDER BY created_at LIMIT ?").bind(now()-86400,limit).all();
  for(const row of stale.results)await db.batch([
    db.prepare("INSERT OR IGNORE INTO platform_engine_asset_purge_queue(id,user_id,storage_key,created_at,not_before) SELECT id,user_id,storage_key,?,? FROM platform_engine_assets WHERE id=? AND status='pending' AND created_at<?").bind(now(),now()+900,row.id,now()-86400),
    db.prepare("DELETE FROM platform_engine_assets WHERE id=? AND status='pending' AND created_at<? AND EXISTS(SELECT 1 FROM platform_engine_asset_purge_queue q WHERE q.id=platform_engine_assets.id)").bind(row.id,now()-86400)
  ]);
  const { results } = await db.prepare('SELECT * FROM platform_engine_asset_purge_queue WHERE not_before<=? ORDER BY created_at LIMIT ?').bind(now(), limit).all();
  let deleted = 0, failed = 0;
  for (const row of results) {
    // Keys are generated by this module, never supplied in upload requests.
    if (!/^engine-private\/[A-Za-z0-9-]{1,100}\/[A-Za-z0-9-]{1,100}\.glb$/.test(row.storage_key)) { failed++; continue; }
    await db.prepare('UPDATE platform_engine_asset_purge_queue SET attempts=attempts+1,last_attempt_at=? WHERE id=?').bind(now(), row.id).run();
    try {
      await bucket.delete(row.storage_key);
      await db.prepare('DELETE FROM platform_engine_asset_purge_queue WHERE id=?').bind(row.id).run(); deleted++;
    } catch { failed++; }
  }
  return { deleted, failed };
}

export async function handleEngineAssets(request, env, path) {
  if (path !== '/engine/assets' && !path.startsWith('/engine/assets/')) return null;
  const method = request.method, db = database(env);
  if (method !== 'GET') requireMutationOrigin(request, env);
  const user = await requireUser(request, env);
  if (!user.emailVerified) fail(403, 'Verify your email before storing models.', 'EMAIL_VERIFICATION_REQUIRED');
  if (method === 'GET') {
    const match = /^\/engine\/assets\/([A-Za-z0-9-]{1,100})$/.exec(path);
    if (!match) fail(404, 'Model asset not found.');
    const row = await db.prepare("SELECT * FROM platform_engine_assets WHERE id=? AND user_id=? AND status='ready'").bind(match[1], user.id).first();
    if (!row) fail(404, 'Model asset not found.');
    let object;
    try { object = await storage(env).get(row.storage_key); }
    catch (error) { if (error instanceof HttpError) throw error; fail(503, 'Private model storage is temporarily unavailable.', 'ENGINE_ASSET_STORAGE_UNAVAILABLE'); }
    if (!object?.body || object.size !== row.size) fail(503, 'The saved model object is unavailable or incomplete.', 'ENGINE_ASSET_OBJECT_UNAVAILABLE');
    return new Response(object.body, { headers: { 'content-type': 'model/gltf-binary', 'content-length': String(row.size),
      'cache-control': 'private, no-store', 'x-content-type-options': 'nosniff', 'content-security-policy': "default-src 'none'; sandbox",
      'content-disposition': `attachment; filename="model.glb"; filename*=UTF-8''${encodeURIComponent(row.name).replace(/'/g, '%27')}`,
      'cross-origin-resource-policy': 'same-origin', 'referrer-policy': 'no-referrer', 'x-asset-sha256': row.sha256 } });
  }
  if (path !== '/engine/assets' || method !== 'POST') fail(405, 'Method not allowed.', 'METHOD_NOT_ALLOWED');
  const bucket = storage(env), name = assetName(request);
  await rate(env, user.id, 'engine-asset-upload', 20, 3600);
  const bytes = await readBytes(request), sha256 = await hashBytes(bytes);
  const existing = await db.prepare('SELECT * FROM platform_engine_assets WHERE user_id=? AND sha256=?').bind(user.id, sha256).first();
  if (existing?.status === 'ready') return json({ asset: publicAsset(existing), reused: true });
  if (existing) fail(409, 'This model upload is already pending. Retry after it finishes.', 'ENGINE_ASSET_PENDING');
  const quotaBytes = bound(env, 'ENGINE_ASSET_QUOTA_BYTES', 512 * 1024 * 1024, 2 * 1024 * 1024 * 1024);
  const quotaCount = bound(env, 'ENGINE_ASSET_QUOTA_COUNT', 200, 1000);
  const asset = { id: id(), user_id: user.id, name, size: bytes.byteLength, sha256, created_at: now() };
  asset.storage_key = `engine-private/${user.id}/${asset.id}.glb`;
  try {
    const result = await db.prepare(`INSERT INTO platform_engine_assets(id,user_id,name,sha256,size,storage_key,status,created_at)
      SELECT ?,?,?,?,?,?,'pending',? WHERE
      (SELECT COUNT(*) FROM platform_engine_assets WHERE user_id=?) < ? AND
      (SELECT COALESCE(SUM(size),0) FROM platform_engine_assets WHERE user_id=?) + ? <= ? AND
      EXISTS(SELECT 1 FROM platform_users WHERE id=? AND status='active')`)
      .bind(asset.id, user.id, name, sha256, asset.size, asset.storage_key, asset.created_at,
        user.id, quotaCount, user.id, asset.size, quotaBytes, user.id).run();
    if (!result.meta.changes) fail(409, 'Private model storage quota has been reached or the account is unavailable.', 'ENGINE_ASSET_QUOTA');
  } catch (error) {
    if (error instanceof HttpError) throw error;
    const raced = await db.prepare('SELECT * FROM platform_engine_assets WHERE user_id=? AND sha256=?').bind(user.id, sha256).first();
    if (raced?.status === 'ready') return json({ asset: publicAsset(raced), reused: true });
    if (raced) fail(409, 'This model upload is already pending. Retry after it finishes.', 'ENGINE_ASSET_PENDING');
    fail(503, 'Model storage could not be reserved. No file was uploaded.', 'ENGINE_ASSET_RESERVATION_FAILED');
  }
  try {
    await bucket.put(asset.storage_key, bytes, { httpMetadata: { contentType: 'model/gltf-binary' }, customMetadata: { sha256 } });
    const ready = await db.prepare("UPDATE platform_engine_assets SET status='ready' WHERE id=? AND user_id=? AND status='pending' AND EXISTS(SELECT 1 FROM platform_users WHERE id=? AND status='active')")
      .bind(asset.id, user.id, user.id).run();
    if (!ready.meta.changes) throw new Error('Account or reservation removed while writing.');
  } catch {
    // Storage timeouts can be ambiguous. Keep the generated object key for an
    // idempotent delayed purge even if put may have failed after writing bytes.
    await db.batch([db.prepare('INSERT OR IGNORE INTO platform_engine_asset_purge_queue(id,user_id,storage_key,created_at,not_before) VALUES(?,?,?,?,?)')
      .bind(asset.id, user.id, asset.storage_key, now(), now() + 900),
      db.prepare('DELETE FROM platform_engine_assets WHERE id=? AND user_id=?').bind(asset.id, user.id)]);
    fail(503, 'The model could not be saved. Keep your local export and retry later.', 'ENGINE_ASSET_WRITE_FAILED');
  }
  return json({ asset: publicAsset(asset) }, 201);
}
