import {input,textArea,select,feedback,notice} from './ui.mjs';
const form=(name,title,content)=>`<details class="panel section"><summary><strong>${title}</strong></summary><form class="form section" data-form="${name}">${content}<button type="submit" class="btn primary">Save Change</button>${feedback()}</form></details>`;
const reason=()=>textArea('reason','Reason for the change','','required minlength="5" maxlength="500"');
export function administrationPanels(path){
 if(path==='/owners-portal/players')return form('owner-roles','Change Account Roles',notice('Choose the complete replacement role set. PLAYER access is retained. Active sessions are revoked. Owner accounts require a separate recovery procedure.')+input('userId','Account ID','text','','required')+`<fieldset style="border:1px solid var(--border);border-radius:8px;padding:17px"><legend>Assign roles</legend><div class="page-stack"><label class="checkbox-row"><input type="checkbox" checked disabled><span>PLAYER — always included</span></label>${['DEVELOPER','PARTNER_DEVELOPER','MODERATOR','CONTENT_MANAGER','FINANCE_ADMIN','PLATFORM_ADMIN'].map(role=>`<label class="checkbox-row"><input type="checkbox" name="roles" value="${role}"><span>${role.replaceAll('_',' ')}</span></label>`).join('')}</div></fieldset>`+notice('Partner developer access cannot be combined with moderator, content manager, finance admin, or platform admin access.')+reason())+form('owner-status','Activate or Suspend an Account',input('userId','Account ID','text','','required')+select('status','Account status',[['active','Active'],['suspended','Suspended']])+notice('Changing status revokes this account’s active sessions.')+reason());
 if(path==='/owners-portal/games')return form('owner-members','Assign a Developer to a Game',input('gameId','Game ID','text','','required')+input('userId','Verified developer account ID','text','','required')+select('permission','Permission',[['edit','Edit assigned game'],['analytics','View game analytics'],['remove','Remove assignment']])+notice('The account must be an active, verified developer or partner developer. This assignment does not grant financial or owner access.')+reason());
 if(['/owners-portal/settings','/owners-portal/costs'].includes(path))return form('owner-threshold','Configure a Usage Threshold',select('key','Usage metric',[['storage_bytes','Storage (bytes)'],['monthly_requests','Monthly requests'],['monthly_bandwidth_bytes','Monthly bandwidth (bytes)'],['daily_upload_bytes','Daily uploads (bytes)']])+input('limitValue','Limit','number','','required min="1" step="1"')+notice('Thresholds configure internal usage controls. They are not a guarantee of provider billing or automatic cost limits.')+reason());
 return '';
}
