import {api,listOf} from './api.mjs';
import {esc,icon,link,btn,badge,notice,head,empty,feedback,input,textArea,select,date,money,table} from './ui.mjs';
const form=(name,content,extra='')=>`<form class="form" data-form="${name}" ${extra}>${content}${feedback()}</form>`;
const submit=(text,cls='btn primary')=>`<button type="submit" class="${cls}">${text}</button>`;
function ownerPublishPanel(state){
 const eligible=(state.ownerGames||[]).filter(game=>game.status==='approved'&&Number(game.priceMinor||0)===0);
 const enabled=state.config.flags?.PUBLIC_CREATOR_PUBLISHING_ENABLED===true;
 return `<section class="panel section"><h2>Publish an Approved Game</h2>${notice(enabled?'Publication requires the exact approved web build, a clean scan attestation, an effective agreement, configured isolated delivery, and recent owner MFA verification.':'Public publishing is disabled. Approved games stay private until reviewed game delivery is configured and publishing is explicitly enabled.')}<div class="section">${enabled&&eligible.length?form('owner-publish',select('gameId','Approved free game',eligible.map(game=>[game.id,game.title]))+textArea('reason','Publication reason','','required minlength="5" maxlength="500"')+'<label class="checkbox-row"><input type="checkbox" name="confirmPublish" required><span>Publish this approved version to the public catalog.</span></label>'+submit('Publish Approved Game')):notice(eligible.length?'Approved games are waiting for publication to be enabled.':'No approved free games are ready for publication.')}</div></section>`;
}
const developerNav=path=>`<nav class="owner-tabs" aria-label="Developer navigation">${[['/developer','My Games'],['/developer/games/new','New Game'],['/developer/analytics','Analytics'],['/developers/docs','Documentation']].map(([href,title])=>link(href,title,'tab '+(href===path?'active':''))).join('')}</nav>`;
const gameFields=g=>input('title','Game title','text',g.title||'','required minlength="2" maxlength="120"')+input('slug','URL slug','text',g.slug||'','required pattern="[a-z0-9]+(-[a-z0-9]+)*" maxlength="72" placeholder="my-game"')+select('kind','Distribution',[['web','Browser game'],['download','Downloadable game'],['both','Browser and download']],g.kind||'web')+input('shortDescription','Short description','text',g.shortDescription||'','maxlength="240" required')+textArea('description','About your game',g.description||'','required maxlength="12000"')+input('genres','Genres, separated by commas','text',(g.genres||[]).join(', '),'maxlength="300"')+input('tags','Tags, separated by commas','text',(g.tags||[]).join(', '),'maxlength="300"')+textArea('controls','Controls',g.metadata?.controls||g.controls||'','maxlength="2000"')+textArea('contentInformation','Content and age guidance',g.metadata?.contentInformation||'','maxlength="2000"')+textArea('systemRequirements','System requirements',g.metadata?.systemRequirements||'','maxlength="3000"');
export async function developerPage(state,path){
 if(!state.user.roles?.some(r=>['DEVELOPER','PARTNER_DEVELOPER','OWNER'].includes(r)))return {html:head('Creator Access','We are preparing a dependable home for independent games.')+empty('Developer access is by invitation.','Join the creator waitlist. Approved developers and partners use this same workspace to submit games.',link('/creators#waitlist','Join the Creator Waitlist','btn primary'),'rocket-launch')};
 const prefix=head('Developer Dashboard','Build your release, track review, and manage your games.')+developerNav(path);
 if(path.endsWith('/analytics')){const data=await api('/developer/analytics');return {html:prefix+`<section class="panel"><h2>Your Game Activity</h2>${data.games?.length?table(['Game','Sessions'],data.games.map(g=>[esc(g.title),esc(g.sessions)])):empty('Activity will appear here.','Your published games will have session totals once players arrive.','','chart-bar')}</section><section class="panel section"><h2>Your Earnings</h2>${notice('Revenue is subject to your explicit monetization agreement. Estimates do not guarantee a payout. Payments and payouts remain disabled.')}${data.earnings?.length?table(['Currency','Status','Amount'],data.earnings.map(e=>[esc(e.currency),esc(e.status),esc(money(e.amountMinor,e.currency))])):'<p class="section muted">No creator obligations have been recorded.</p>'}</section>`};}
 if(path.endsWith('/new'))return {html:prefix+`<section class="panel"><h2>Create a Game Listing</h2>${form('create-game',gameFields({})+submit('Create Draft'))}</section>`};
 const match=path.match(/^\/developer\/games\/([^/]+)$/);
 if(match){const data=await api('/developer/games/'+encodeURIComponent(match[1]));const g=data.game;state.developerGame=g;state.versions=data.versions||[];if(data.canEdit===false)return {html:prefix+notice('You have analytics access to this assigned game. Editing, uploading and submission controls are not available to your account.')+`<section class="panel section"><div class="panel-title"><h2>${esc(g.title)}</h2>${badge(g.status,'neutral')}</div><p class="section">${esc(g.description||g.shortDescription||'No description provided.')}</p><div class="section">${link('/developer/analytics','View Game Analytics','btn primary')}</div></section>`};const enabled=state.config.flags?.PUBLIC_CREATOR_UPLOADS_ENABLED===true;
 return {html:prefix+`<div class="page-stack"><section class="panel"><div class="panel-title"><h2>${esc(g.title)}</h2>${badge(g.status,'neutral')}</div><div class="section">${form('edit-game',gameFields(g)+submit('Save Listing'),`data-id="${esc(g.id)}"`)}</div></section><section class="panel"><h2>Upload a Game Version</h2>${enabled?notice('Every build is held in quarantine until validation and scanning complete. Uploading does not publish your game.'):notice('Build uploads are currently closed. Your draft remains saved; uploads require storage, scanning and isolated game delivery to be configured.')}<div class="section">${form('upload-game',`<fieldset ${enabled?'':'disabled'} style="border:0;padding:0;margin:0;display:grid;gap:16px">`+select('platform','Build platform',[['web','Browser / Web'],['windows','Windows'],['macos','macOS'],['linux','Linux']])+input('version','Version','text','','required pattern="[0-9]+\.[0-9]+\.[0-9]+(-[A-Za-z0-9.-]+)?" placeholder="1.0.0"')+'<label>Game build ZIP<input type="file" name="build" accept=".zip,application/zip" required><small>Upload one complete ZIP. Browser builds need index.html at the root.</small></label>'+textArea('releaseNotes','Release notes','','maxlength="4000"')+submit('Upload to Quarantine')+'</fieldset><progress id="upload-progress" value="0" max="100" hidden style="width:100%"></progress>',`data-id="${esc(g.id)}"`)}</div></section><section class="panel"><h2>Versions</h2>${state.versions.length?table(['Version','Platform','Status','Scan','Uploaded'],state.versions.map(v=>[esc(v.version),esc(v.platform),badge(v.status,'neutral'),esc(v.scan_status||'pending'),date(v.created_at)])):'<p class="muted">No builds uploaded yet.</p>'}</section><section class="panel"><h2>Submit for Review</h2><p>Only a build that has completed validation and scanning can enter review. Review never creates revenue rights.</p><div class="section">${form('submit-game',select('versionId','Validated build',state.versions.filter(v=>v.status==='ready'&&v.scan_status==='clean').map(v=>[v.id,v.version+' · '+v.platform]))+'<label class="checkbox-row"><input type="checkbox" name="rightsConfirmed" required><span>I own this game or have the rights to publish the build, assets, music, and other included content.</span></label>'+submit('Submit Game for Review'),`data-id="${esc(g.id)}"`)}</div></section></div>`};}
 const data=await api('/developer/games');const games=listOf(data,'games');return {html:prefix+(games.length?`<section class="panel">${games.map(g=>`<article class="list-row">${icon('game-controller')}<div><h3>${esc(g.title)}</h3><p>Updated ${date(g.updatedAt)}</p></div>${badge(g.status,'neutral')}${link('/developer/games/'+encodeURIComponent(g.id),'View Game','btn small')}</article>`).join('')}</section>`:empty('Your first release starts here.','Create a draft, prepare your build, and follow the submission guide.',link('/developer/games/new','Create Game Draft','btn primary'),'game-controller'))};
}
const ownerRoutes=[['','Overview'],['commerce','Commerce & Revenue'],['ads','Advertising'],['sales','Premium Sales'],['creators','Creators'],['agreements','Agreements'],['payouts','Payouts'],['games','Games'],['players','Players'],['rewards','Rewards'],['engine','Game Engine'],['infrastructure','Infrastructure'],['storage','Storage'],['costs','Costs / Usage'],['security','Security'],['audit','Audit Log'],['notifications','Notifications'],['settings','Platform Settings']];
export async function ownerPage(state,path){
 if(!state.user.roles?.includes('OWNER'))return {html:head('Owner Portal')+empty('Owner access required.','Your current account does not have permission to access this portal.',link('/profile','Back to My Account','btn'),'shield-check')};
 const key=path.slice('/owners-portal'.length).replace(/^\//,'')||'';
 const prefix=`<p class="owner-badge">${icon('shield-check')} OWNER PORTAL</p>`+head('The business behind the worlds.','Private operations, review and platform controls.')+`<nav class="owner-tabs" aria-label="Owner portal navigation">${ownerRoutes.map(([route,title])=>link('/owners-portal'+(route?'/'+route:''),title,'tab '+(route===key?'active':''))).join('')}</nav>`;
 if(!key){const data=await api('/owner/overview');return {html:prefix+`<div class="stat-grid">${[['players','Active Players'],['games','Published Games'],['awaitingReview','Awaiting Review'],['quarantinedUploads','Quarantined Uploads'],['projects','Engine Projects']].map(([k,label])=>`<div class="stat-card"><small>${label}</small><strong>${esc(data[k]??'Unavailable')}</strong></div>`).join('')}</div><section class="panel section"><h2>Commerce & Revenue</h2>${data.revenue?.length?table(['Currency','Status','Gross','Creator obligation','Platform allocation'],data.revenue.map(r=>[esc(r.currency),esc(r.status),money(r.grossMinor,r.currency),money(r.creatorMinor,r.currency),money(r.platformMinor,r.currency)])):notice('No revenue events have been recorded. Payment, ad, and payout providers are disabled.')}</section><section class="panel section"><h2>Operations</h2><div class="inline-actions">${link('/owners-portal/games','Review Games','btn')}${link('/owners-portal/security','Security Events','btn')}${link('/owners-portal/settings','Feature Controls','btn')}</div></section>`};}
 if(key==='settings'){const data=await api('/owner/flags');const flags=data.flags||{};return {html:prefix+notice('Sensitive changes require recent password and MFA verification. Provider activation remains blocked until readiness and explicit go-live approval. '+link('/settings','Verify identity','text-link'))+`<section class="panel section"><h2>Feature Controls</h2>${form('owner-flag',select('key','Feature',Object.keys(flags).map(k=>[k,k.replaceAll('_',' ')+' · '+(flags[k]?'ON':'OFF')]))+select('enabled','Set state',[['false','Disabled'],['true','Enabled']])+textArea('reason','Reason for the change','','required maxlength="500"')+submit('Apply Feature Change'))}</section>`};}
 if(key==='games'){const data=await api('/owner/games');state.ownerGames=data.games||[];return {html:prefix+`<section class="panel"><h2>Game Review Queue</h2>${state.ownerGames.length?table(['Title','Status','Developer','Updated'],state.ownerGames.map(g=>[esc(g.title),badge(g.status,'neutral'),esc(g.developerId),date(g.updatedAt)])):empty('No submissions awaiting review.','Developer submissions will appear here once uploaded and validated.','','clipboard-text')}</section>${state.ownerGames.length?`<section class="panel section"><h2>Record a Review Decision</h2>${form('owner-review',select('gameId','Game',state.ownerGames.map(g=>[g.id,g.title+' · '+g.status]))+select('decision','Decision',[['changes_requested','Request changes'],['approve','Approve after review'],['reject','Reject'],['suspend','Suspend']])+textArea('reason','Review notes','','required maxlength="1500"')+submit('Record Decision'))}</section>`:''}${ownerPublishPanel(state)}`};}
 if(key==='agreements'){const data=await api('/owner/agreements');state.agreements=listOf(data);return {html:prefix+notice('Agreements preserve version history. Terms are set intentionally; uploading a game alone does not create a revenue entitlement.')+`<section class="panel section"><h2>Agreement Versions</h2>${state.agreements.length?table(['Name','Classification','Version','Effective'],state.agreements.map(a=>[esc(a.name),esc(a.type),esc(a.version),date(a.effective_at)])):'<p class="muted">No agreements recorded.</p>'}</section><section class="panel section"><h2>Create an Agreement</h2>${form('owner-agreement',input('name','Agreement name','text','','required maxlength="120"')+select('type','Classification',[['platform_owned','Platform owned'],['creator_revenue_share','Creator revenue share'],['custom','Custom agreement']])+input('creatorId','Creator account ID (required for creator/custom agreements)','text','','maxlength="100"')+input('effectiveAt','Effective date and time','datetime-local','','required')+input('currency','Currency','text','USD','required pattern="[A-Z]{3}" maxlength="3"')+`<div class="notice">${icon('info')}<p>Enter creator shares explicitly for each category. The platform receives the remainder. Platform-owned agreements must use zero creator share.</p></div><div class="form-row">${['rewarded_ads','interstitial_ads','premium_sales','dlc','iap','subscriptions','sponsorships','promotions','other'].map(k=>input(k,k.replaceAll('_',' ')+' creator %','number','','required min="0" max="100" step="0.01"')).join('')}</div>`+input('minimumPayoutMinor','Minimum payout in minor currency units','number','','required min="0" step="1"')+input('paymentSchedule','Payment schedule','text','','required maxlength="100" placeholder="Specify the agreement terms"')+textArea('publicNotes','Creator-visible notes','','maxlength="2000"')+textArea('internalNotes','Private notes','','maxlength="4000"')+submit('Create Agreement Version'))}</section><section class="panel section"><h2>Assign an Agreement to a Game</h2>${form('owner-assignment',input('gameId','Game ID','text','','required')+select('versionId','Agreement version',state.agreements.map(a=>[a.versionId,a.name+' · v'+a.version]))+input('effectiveAt','Effective date and time','datetime-local','','required')+submit('Assign Agreement'))}</section>`};}
 if(['creators','players'].includes(key)){const data=await api('/owner/'+key);return {html:prefix+`<section class="panel"><h2>${key==='players'?'Players':'Creators'}</h2>${listOf(data).length?table(['Name','Username','Status','Account ID'],listOf(data).map(u=>[esc(u.displayName),esc(u.username),esc(u.status),esc(u.id)])):empty('No records to display.','Accounts in this category will appear here.','','users-three')}</section>`};}
 if(['audit','security'].includes(key)){const data=await api('/owner/'+key);return {html:prefix+`<section class="panel"><h2>${key==='audit'?'Audit Log':'Security Events'}</h2>${listOf(data).length?table(['Date','Action','Actor','Target','Result'],listOf(data).map(e=>[date(e.created_at),esc(e.action),esc(e.actor_id),esc(e.target_id),esc(e.result)])):empty('No events to display.','Recorded platform events will appear here.','','shield-check')}</section>`};}
 if(['infrastructure','storage','costs'].includes(key)){const data=await api('/owner/'+(key==='costs'?'infrastructure':key));return {html:prefix+`<div class="stat-grid"><div class="stat-card"><small>Tracked Upload Storage</small><strong>${esc(((data.internalEstimate?.bytes||0)/1024/1024).toFixed(1))} MB</strong><span>Internal estimate, not provider billing</span></div><div class="stat-card"><small>Tracked Uploads</small><strong>${esc(data.internalEstimate?.uploads||0)}</strong></div></div><section class="section">${notice('Cloudflare billing and provider usage have not been connected. These internal estimates do not represent a provider invoice.')}</section>`};}
 if(['commerce','ads','sales','payouts'].includes(key)){const data=await api('/owner/'+key);return {html:prefix+empty('Provider reporting is not active.',data.message||'No provider connection is configured. No revenue or payout is being generated.',link('/owners-portal/agreements','Manage Agreements','btn'),'chart-bar')};}
 return {html:prefix+empty('This operational view is not active yet.','The platform has no connected data for this view. Use Overview, Games, Agreements, Security, and Feature Controls to manage the available systems.',link('/owners-portal','Back to Overview','btn'),'sliders')};
}

