import {esc,link,head,notice} from './ui.mjs';

export const LEGAL_VERSION = '2026-10-01-draft';
export const LEGAL_EMAIL = 'crateshipstudios@gmail.com';
const contact = `<a href="mailto:${LEGAL_EMAIL}" class="text-link">${LEGAL_EMAIL}</a>`;
const p = text => `<p>${text}</p>`;
const section = (title,text) => [title,p(text)];
// Draft commercial terms are deliberately separate from effective, signed
// agreement versions in the database. Rendering these pages grants no rights.
export const legalDocuments = {
 '/terms': {title:'Terms of Service',summary:'Accounts, game access, responsibilities, and your rights.',sections:[
  section('About these terms','Crate Ship Games is the service at crateshipgames.com. These are prelaunch draft terms, version '+LEGAL_VERSION+'. The legal operator, business address, governing jurisdiction, and age rules are awaiting owner confirmation. No new commercial contract or revenue entitlement is created by viewing this draft. Contact '+contact+' with questions.'),
  section('Accounts and eligibility','Provide accurate account information, secure your sign-in, and tell us about unauthorized access. Do not impersonate others or share an account to evade restrictions. Age eligibility and parental-consent requirements must be finalized before the commercial launch; this draft does not establish a service for children under 13. Monetized creators must have legal capacity to contract and satisfy the payment provider’s verification requirements.'),
  section('Playing and buying games','Game availability, controls, compatible devices, and content warnings should be shown on each listing. A free demo is a limited version, not ownership of the full game. When sales launch, the price, delivery format, license, and refund terms must be displayed before checkout. Paid games, checkout, ads, and creator payouts are currently disabled. Virtual rewards are not cash, investments, or a promise of payment.'),
  section('Licenses and ownership','Creators retain ownership of their games and assets. Players receive only the usage rights identified in the applicable game license; buying access does not transfer copyright. Do not copy, resell, redistribute, or bypass access controls without permission or a right provided by law. Open-source and third-party licenses continue to apply. The separate Creator Agreement describes hosting permissions.'),
  section('Safe use and moderation','Follow the Acceptable Use Policy and Community Guidelines. We may restrict unsafe content or accounts to protect users, comply with law, or address violations. Where appropriate, we explain the decision and accept an appeal through our contact email. Urgent safety action may come first. Removing a listing does not erase applicable consumer rights or legitimate earned amounts.'),
  section('Availability and responsibility','Games may contain bugs or become unavailable. Keep your own backups and do not rely on uninterrupted access. To the extent permitted by applicable law, the service is offered as available without additional guarantees. Nothing in these drafts excludes non-waivable consumer rights or liability that the law does not allow to be excluded. Any specific liability limit or dispute clause requires jurisdiction-specific review before adoption.'),
  section('Changes, disputes, and ending use','You may stop using the service and use Settings to manage your account or request deletion. Relevant rights, security, and accounting records may need to be retained. Contact us first about a dispute without giving up any legal remedy. Material changes to commercial terms require notice and the appropriate acceptance process; updated drafts do not retroactively alter a signed agreement. No arbitration clause or foreign court requirement is being adopted by this draft.')
 ]},
 '/privacy': {title:'Privacy Notice',summary:'What the platform processes, why, and how to contact us.',sections:[
  section('Scope and contact','This notice describes the platform’s inspected prelaunch implementation as of October 1, 2026. The controller’s legal identity, address, applicable jurisdictions, and final retention schedule still require confirmation. Privacy questions and requests can be sent to '+contact+'. Creator game code and external model services can have their own practices; creators must disclose additional collection.'),
  section('Information you provide','Account services process email, username, display name, verification status, and sign-in records. Google Firebase Authentication handles password and Google sign-in flows; Crate Ship verifies sign-in tokens and creates a platform session. Account features can store preferences, favorites, library entries, play history, progress, uploaded materials, creator listings, reports, and support correspondence. Do not put private credentials into game uploads.'),
  section('Technical and activity information','Hosting and security services receive network and device information needed to deliver pages and protect accounts. Our visit counter receives a page category, IP address, and user-agent information, derives a keyed daily visitor identifier, and stores visit counts and that identifier rather than the raw IP in the visit tables. This is pseudonymous measurement, not a guarantee of anonymous processing. The visit counter skips browsers sending supported Do Not Track or Global Privacy Control signals. Security processing and infrastructure logs are separate.'),
  section('Purposes and providers','We use information to operate accounts, deliver and review games, retain progress, respond to requests, prevent misuse, and understand service use. Cloudflare provides hosting, storage, and platform infrastructure; Google Firebase provides authentication. Information may also be provided when necessary for legal obligations, safety, or a properly evaluated business transfer. Public creator/game information is visible when a listing is published. Provider systems may process information outside your country. Applicable legal bases and international transfer safeguards must be documented before expanding the service.'),
  section('Advertising and payments','Platform advertising, checkout, and creator payouts are currently disabled. Before activation, this notice and the consent experience must identify the actual ad/payment providers, their data uses, applicable opt-outs, and payment verification requirements. An account preference alone does not activate a provider. We do not currently run platform personalized advertising. We are not promising that future ad processing is exempt from privacy sale/sharing rules.'),
  section('Storage, security, and retention','A secure HttpOnly session cookie supports sign-in. Browser storage can hold pending signup details and local project data. Access controls and encrypted secrets reduce risk but cannot guarantee perfect security. Account deletion clears or de-identifies the platform profile and supported personal feature records; financial, rights, moderation, and security records may remain where needed. Firebase identity deletion, backups, and retained uploads require coordinated handling. We do not promise immediate deletion from every system; the final category-by-category retention schedule is pending.'),
  section('Your choices and requests','Use Settings for profile, session, preference, and account-deletion controls, or email us to request access, correction, deletion, or information about processing. Depending on applicable law, you may also have portability, objection, restriction, consent-withdrawal, and sale/sharing opt-out rights. We verify requests proportionately and explain any lawful limitation; do not send a password or identity document in an ordinary email. You may complain to the relevant privacy authority. Statutory rights apply whether or not they are listed here.'),
  section('Children and updates','A child account/parental-consent program is not implemented. The owner must confirm the intended audience and age controls before inviting children or enabling ads. If you believe a child’s information was provided without required permission, contact us. We will investigate and take appropriate action. Material privacy changes will be disclosed before the relevant new processing starts.')
 ]},
 '/cookies': {title:'Cookies & Privacy Choices',summary:'Essential sign-in storage and planned advertising choices.',sections:[
  section('Essential storage','The platform uses a secure HttpOnly sign-in cookie with a maximum normal session duration of 30 days; owner sessions have shorter limits. Sign-in providers can use storage needed for their own flows. Pending signup profile details are stored locally until the platform exchange clears them. Local projects can remain on your device until you remove them. These functions are distinct from advertising consent.'),
  section('Measurement','The current first-party visit counter does not create a tracking cookie. It uses daily pseudonymous identifiers derived on the server and aggregate page counts, as explained in the Privacy Notice. It respects the supported Do Not Track and Global Privacy Control signals for visit counting. It is not tied to the account’s optional analytics toggle, so that toggle must not be described as disabling this counter.'),
  section('Advertising choices before launch','No platform ad provider is active. Before personalized ads are offered, the platform must provide applicable region-specific consent and opt-out controls, explain purposes and vendors, allow withdrawal, and honor the required signals. Google’s requirements include a certified consent platform for personalized advertising in the EEA, UK, and Switzerland. A disabled preference switch is not a working consent platform.'),
  section('Managing storage','Use your browser’s cookie/storage controls and the platform’s Settings. Blocking essential storage can prevent sign-in; clearing local storage may remove unsaved local work. Contact '+contact+' for privacy help. The final cookie/vendor inventory must be updated when any new integration launches.')
 ]},
 '/creator-agreement': {title:'Creator Agreement',summary:'Rights, review, demos, and proposed commercial terms.',sections:[
  section('Draft agreement and acceptance','This is the proposed creator agreement, not an automatically effective contract. Commercial participation requires a versioned agreement assigned to your game and an auditable acceptance process. Creator signup or uploading alone does not create payment rights. Operator details, age/capacity rules, and final terms must be confirmed before monetization.'),
  section('You keep your work','You retain ownership. Under an effective agreement, you grant the platform a non-exclusive permission to store, reproduce, technically adapt, host, display, and distribute the submitted build and approved artwork as needed to operate the listing and market that game. This does not authorize selling your source code, claiming ownership, or unrelated AI training. Any additional permission requires a separate agreement.'),
  section('Your responsibilities','You must have the rights to every included asset, code dependency, music track, likeness, and trademark, including AI-assisted material and required attribution. Provide accurate descriptions, controls, supported devices, age/content guidance, licenses, and system requirements. Disclose game-level data collection. Do not include secret keys, malware, hidden mining, deceptive purchases, or unauthorized advertising SDKs.'),
  section('Upload and review','Browser builds require a root index.html and the published packaging limits. Uploads remain private until checks, human review, and release complete. Current automated checks cover archive structure, file limits, prohibited executable signatures, and selected suspicious-code patterns; they are not a comprehensive antivirus guarantee. Passing a check is not approval. Public uploads and publishing are currently closed pending infrastructure setup.'),
  section('Free demos and full games','The proposed free-hosting program is for substantial, clearly labeled playable demos, with a creator’s option to sell a separate full version. A demo should offer a meaningful level or core gameplay loop, disclose its limitations, and avoid misleading promises. Demo and full-version listings must be linked and reviewed. Standalone full free games require a separate approved classification. This workflow and its fields still need implementation.'),
  section('Proposed shares','For creator games, the proposed standard is 70% creator / 30% platform of finalized eligible ad revenue and 80% creator / 20% platform of the game’s pre-tax sale price, after refunds. The proposed sales policy pays standard processing and platform payout costs from the platform’s 20%, rather than silently deducting them from the creator’s 80%. This fee policy must be confirmed and reflected in the ledger before activation. Custom terms require an explicit agreement. Platform-owned games do not create a third-party creator share.'),
  section('Earnings and ending distribution','No earnings are guaranteed. Finalized provider revenue, adjustments, disputed payments, reserves, and payouts must be reported separately. The Monetization & Payout Policy explains the proposed process. You may request removal or termination by email. Safety removals can happen sooner; already purchased licenses, legally required retention, unresolved disputes, and valid earned amounts must be handled under the effective agreement. Specific notice periods and indemnity terms need final legal review.')
 ]},
 '/payout-policy': {title:'Monetization & Payout Policy',summary:'How proposed revenue shares and payment records should work.',sections:[
  section('Current status','Ads, paid checkout, paid delivery, and creator payouts are not enabled. Figures in this draft are proposals, not accrued earnings. Only a signed effective agreement and verified provider events can establish a payable balance.'),
  section('Advertising share','The proposed split is 70% to the creator and 30% to Crate Ship from ad proceeds attributable to that game and finalized by the provider, after provider deductions and invalid-traffic adjustments. Hosting and ordinary platform costs are funded from Crate Ship’s share; they should not become hidden additional deductions. Client ad callbacks or view counts alone do not prove payable income. We must reconcile per-game provider reports before recording finalized earnings.'),
  section('Game sales share','The proposed split is 80% creator / 20% platform of the pre-tax sale amount, adjusted for refunds. Taxes are not creator revenue. Standard Stripe processing and Connect costs are proposed to come from the platform’s share. Currency conversion, unusual payout methods, dispute costs, and any reserve must be disclosed in the effective agreement before use. Example without tax or refund: a $10 sale allocates $8 to the creator and $2 to the platform before the platform pays its provider fees.'),
  section('Onboarding and payout timing','Creators must complete the required identity, tax, country, and payout verification before earning or receiving money. The minimum payout, currency, settlement delay, reserve rules, and schedule must be disclosed in the agreement; no minimum or payment date is adopted by this draft. Funds are payable only after provider finalization, applicable holds, and verification. Stripe Connect is planned for sales; any ad payout arrangement must be supported and approved by its provider.'),
  section('Refunds, fraud, and reporting','Duplicate provider events must not create duplicate balances. Corrections are recorded as adjustments, preserving accounting history. Refunds and disputes can reverse attributable earnings and transfers under disclosed rules. Temporary review of suspicious activity should be limited and explained where possible. Creators should see estimates, finalized amounts, deductions, amounts held, and amounts paid separately, and may dispute a report through '+contact+'.'),
  section('Tax and changes','Creators are responsible for their applicable income-tax obligations, while the platform’s collection/reporting duties depend on the selling model and law. Required tax forms and transaction tax handling must be configured before payouts. New rates apply prospectively under a new accepted agreement version; they must not rewrite historical transactions.')
 ]},
 '/refund-policy': {title:'Refund & Cancellation Policy',summary:'Current availability and proposed protections for game buyers.',sections:[
  section('No checkout yet','Crate Ship is not currently accepting game purchases. This is a proposed policy for a future sales launch, not a representation that live refunds or downloads already work. Existing transactions from other products or stores remain subject to those products’ terms.'),
  section('Proposed refund requests','The proposed policy permits requests within 14 days of purchase for failed delivery, a materially defective game, or a listing that substantially misrepresents the product. For a change-of-mind request, eligibility will depend on delivery/access status and the policy presented before checkout. Mandatory consumer rights, including any longer statutory remedy, take priority. A download alone does not remove rights concerning a defective or misdescribed product.'),
  section('Digital delivery and consent','Before checkout, clearly show compatibility, total price, delivery method, and applicable cancellation rights. Where law permits a cancellation right to end on immediate digital delivery, obtain the required express consent and acknowledgement separately. Do not treat ordinary account signup or opening a free demo as that consent. This consent workflow is not yet implemented.'),
  section('How to request help','Email '+contact+' with your order reference, game title, and a brief explanation. Do not include full card numbers, passwords, or secret keys. We may ask for information needed to resolve delivery or verify the order. Approved refunds must be returned through the original provider when supported; timing depends on that provider. Do not promise a completed refund before confirmation.'),
  section('Consequences and disputes','A refund may revoke the corresponding paid license or access while leaving unrelated purchases intact. Creator/platform allocations must be reversed consistently. Free demos have no purchase price to refund. Report unauthorized charges promptly to the payment provider and us. The final policy and request process must be operational before accepting sales.')
 ]},
 '/acceptable-use': {title:'Acceptable Use Policy',summary:'Rules for safe games, listings, and platform access.',sections:[
  section('Prohibited conduct','Do not upload unlawful content, malicious code, credential theft, hidden mining, pirated games, or material you have no right to distribute. Do not exploit children, threaten people, promote violence against protected groups, disclose someone’s private information, commit fraud, or impersonate another person or business.'),
  section('Technical and commercial integrity','Do not bypass the player sandbox, access other users’ data, evade moderation, attack infrastructure, manipulate ad traffic, buy fake engagement, automate ad viewing, or interfere with billing/payout records. Do not add undisclosed trackers, unauthorized ad code, gambling, real-money prizes, or regulated transactions to a game. Report vulnerabilities privately and avoid accessing more information than necessary.'),
  section('Honest listings and enforcement','Use accurate screenshots and descriptions, disclose content warnings and compatibility, and do not claim fake reviews, prizes, or earnings. We can quarantine, reject, suspend, or remove content and accounts as appropriate. Security checks reduce risk; they do not certify every upload as harmless. Report problems through a game’s concern form or '+contact+'; appeals should identify the listing and decision.')
 ]},
 '/community-guidelines': {title:'Community Guidelines',summary:'Respectful conduct and understandable moderation.',sections:[
  section('Treat people with respect','Keep criticism about the game or work. Harassment, hate, threats, doxxing, sexual exploitation, spam, deceptive promotions, and targeted abuse are not welcome. Respect creators’ ownership and other players’ privacy. Do not pressure anyone to reveal personal information or move into an unsafe conversation.'),
  section('Reviews and reporting','Reviews and discussions, when enabled, must reflect genuine experience and disclose incentives. Do not manipulate ratings or retaliate against reports. Flag unsafe or misleading content through the available reporting controls or '+contact+'. Community discussion features are currently on the roadmap; this page does not claim they are active.'),
  section('Moderation and appeals','Actions may include a warning, removal, restrictions, or account suspension based on severity and repeated behavior. Where appropriate we explain the reason, allow an appeal by email, and reassess with relevant evidence. Serious safety issues can require immediate action. These rules apply alongside the Acceptable Use and Copyright policies.')
 ]},
 '/copyright': {title:'Copyright & Takedown Requests',summary:'Report unauthorized use and understand the review process.',sections:[
  section('Rights and contact','Creators must own or license uploaded material. Send copyright complaints to '+contact+'. The operator’s designated-agent name, address, telephone, and registration still require completion; this page does not claim DMCA safe-harbor registration.'),
  section('A copyright notice','Identify the protected work and exact allegedly infringing URLs, provide your contact details and signature, and state your good-faith belief that the use is unauthorized. State that the information is accurate and that you are authorized to act for the rights holder under penalty of perjury. Misleading notices may have legal consequences.'),
  section('Removal and response','We review valid notices, restrict infringing material as appropriate, and notify the uploader. A counter-notice should identify the removed material, include the uploader’s signature and contact details, assert mistake or misidentification under penalty of perjury, and include the required court-jurisdiction and service-of-process statements. Where the DMCA process applies, restoration follows its 10–14-business-day rule unless qualifying court-action notice is received.'),
  section('Repeat infringement','The proposed policy terminates repeat infringers in appropriate circumstances and addresses attempts to evade restrictions. Notices and counter-notices may be shared with the other party as required. Privacy or impersonation concerns that do not involve copyright can be reported separately to the same contact. The agent registration and operational response process must be finished before public creator hosting.')
 ]}
};

export const LEGAL_PATHS = Object.freeze(['/legal', ...Object.keys(legalDocuments)]);
export function legalPage(path) {
 const status = notice('Prelaunch drafts · Updated October 1, 2026. Business identity, jurisdiction, age rules, and final commercial policies are awaiting confirmation. Ads, purchases, and payouts remain off.');
 if (path === '/legal') return {html:head('Legal & Trust Center','Clear rules for players and creators.')+status+`<div class="page-grid section">${Object.entries(legalDocuments).map(([url,doc])=>link(url,`<h2>${esc(doc.title)}</h2><p>${esc(doc.summary)}</p>`,'panel')).join('')}</div><section class="panel section"><h2>Questions or requests?</h2>${p('Contact '+contact+' for support, privacy, copyright, or policy questions. These drafts do not replace review of the platform’s actual practices and applicable law.')}</section>`};
 const doc = legalDocuments[path]; if (!doc) return null;
 return {html:link('/legal','← Legal & Trust Center','text-link')+head(doc.title,doc.summary)+status+`<nav class="legal-toc section" aria-label="On this page">${doc.sections.map(([title],i)=>link(path+'#legal-section-'+(i+1),esc(title),'text-link')).join('')}</nav><article class="panel doc-content section">${doc.sections.map(([title,body],i)=>`<section id="legal-section-${i+1}" class="legal-section"><h2>${esc(title)}</h2>${body}</section>`).join('')}</article><p class="legal-contact section">Version ${LEGAL_VERSION} · ${contact} · ${link('/legal','All policies','text-link')}</p>`};
}
