import {api,listOf} from './api.mjs';
import {esc,icon,link,btn,badge,notice,head,empty,feedback,input,textArea,select,date,money,safeImage,gameGrid,table} from './ui.mjs';
import {creatorSections} from './shell.mjs';
export const needsUser = ['/library','/favorites','/history','/rewards','/profile','/settings','/notifications','/engine/projects','/developer','/owners-portal'];
const features=['favorites','history','library'];
const form=(name,content,extra='')=>`<form class="form" data-form="${name}" ${extra}>${content}${feedback()}</form>`;
const submit=(text,cls='btn primary')=>`<button type="submit" class="${cls}">${text}</button>`;
const sectionHead=(symbol,title,description,href)=>`<div class="section-heading"><div>${icon(symbol)}<h2>${title}</h2><p>${description}</p></div>${link(href,'See All '+icon('arrow-right'),'')}</div>`;
const shelf=(title,description,symbol)=>`<div class="empty-shelf">${icon(symbol)}<div><h3>${title}</h3><p>${description}</p></div></div>`;
export async function homePage(state){
 const data=await api('/catalog?limit=16'); const games=listOf(data,'games'); state.games=games;
 const featured=games.filter(g=>g.featured); const hero=featured[0];
 const free=games.filter(g=>g.kind!=='premium'&&!(g.priceCents>0)); const premium=games.filter(g=>g.kind==='premium'||g.priceCents>0);
 return {html:`<section class="hero"><img class="hero-art" src="${esc(hero?safeImage(hero.heroUrl||hero.coverUrl):'/platform/media/world-hero.png')}" alt="${hero?esc(hero.title):'A vast fantasy world with a castle, wild forests and distant mountains'}"><div class="hero-scrim"></div><div class="hero-content"><p class="eyebrow">${hero?'Featured Game':'A new world of play'}</p><h1>${hero?esc(hero.title):'Find your next adventure.'}</h1><p class="hero-tagline">${hero?esc(hero.tagline||'A new world is waiting.'):'Good games. Brighter worlds.'}</p><p class="hero-copy">${hero?esc(hero.shortDescription||hero.description||'Discover this independent game.'):'Discover independent games, collect your favorites, and create a world of your own.'}</p><div class="hero-actions">${link(hero?'/game/'+encodeURIComponent(hero.slug):'/games',icon('game-controller')+(hero?' Play Now':' Explore Games'),'btn primary')}${link(hero?'/game/'+encodeURIComponent(hero.slug):'/creators',hero?'View Details':'Meet the Creator Hub','btn ghost')}</div></div>${hero?'':'<span class="hero-status">Launch catalog in preparation</span>'}</section><section class="section home-games">${sectionHead('star','Featured Games','Handpicked experiences from our team.','/games')}${featured.length?gameGrid(featured.slice(0,4)):shelf('The next great discovery starts here.','Our launch collection is being prepared. Approved games will appear here with real details and playable builds.','sparkle')}</section><section class="section home-games">${sectionHead('game-controller','Play Free With Ads','Great games. Free to play.','/games/free')}${free.length?gameGrid(free.slice(0,4)):shelf('More play. No ticket required.','Free games are on the way. Advertising and ad rewards remain off until the platform is ready.','game-controller')}</section><section class="section home-games">${sectionHead('shopping-cart','Buy Premium Games','Bigger worlds. Deeper experiences.','/games/premium')}${premium.length?gameGrid(premium.slice(0,4)):shelf('Make room for something memorable.','Explore premium releases when creators launch. Checkout is not available yet.','shopping-bag')}</section>`,full:creatorSections()};
}
export async function catalogPage(state,path){
 const params=new URLSearchParams(location.search);const q=params.get('q')||'';const page=Math.max(1,Number(params.get('page'))||1);const kind=path.endsWith('/free')?'free':path.endsWith('/premium')?'premium':'';
 const data=await api('/catalog?'+new URLSearchParams({q,kind,page:String(page)})); const games=listOf(data,'games');state.games=games;
 return {html:head(kind==='premium'?'Premium Games':kind==='free'?'Play Free Games':'Discover Games',q?`Results for “${q}”`:'Independent worlds. Fresh adventures. Your next favorite game.')+`<form class="toolbar" data-form="search">${input('q','Search the catalog','search',q,'placeholder="Search games or creators"')}<button class="btn primary" type="submit">${icon('magnifying-glass')}Search</button></form><div class="toolbar tabs">${[['/games','All games'],['/games/free','Free games'],['/games/premium','Premium games']].map(([href,t])=>link(href,t,'tab '+(href===path?'active':''))).join('')}</div>${kind==='premium'?notice('Purchases are disabled while commerce is being prepared. No payment will be collected.') : ''}<div class="section">${games.length?gameGrid(games):empty(q?'No games matched your search.':'The launch catalog is taking shape.',q?'Try another title, creator, or genre.':'Reviewed games will appear here as they become available.',link(q?'/games':'/creators',q?'Browse all games':'Explore the creator program','btn primary'))}</div>${data.total>games.length?`<div class="pagination">${page>1?link(path+'?'+new URLSearchParams({q,page:String(page-1)}),'Previous','btn small'):''}<span>Page ${page}</span>${data.total>page*(data.pageSize||24)?link(path+'?'+new URLSearchParams({q,page:String(page+1)}),'Next','btn small'):''}</div>`:''}`};
}
export async function gamePage(state,slug){
 const data=await api('/catalog/'+encodeURIComponent(slug));const game=data.game; if(!game)throw new Error('This game could not be found.');state.currentGame=game;
 const premium=game.kind==='premium'||game.priceCents>0;
 return {html:`${link('/games',icon('arrow-left')+' Back to games','text-link')}<div class="section"><img class="detail-cover" src="${esc(safeImage(game.heroUrl||game.coverUrl||game.coverImage))}" alt="${esc(game.title)}"></div><div class="game-detail-title"><div><p class="eyebrow">${esc(game.genre||'Independent game')}</p><h1>${esc(game.title)}</h1><p class="muted">By ${esc(game.creatorName||game.developerName||'Independent creator')}</p></div>${btn('favorite',icon('heart')+' Favorite','btn',`data-id="${esc(game.id)}" aria-pressed="${!!game.isFavorite}"`)}</div><div class="inline-actions">${premium?`<button class="btn primary" disabled>Purchases coming soon</button>`:btn('play-game',icon('play')+' Play Game','btn primary')+btn('claim-game',icon('plus')+' Add to Library','btn')}${premium&&game.priceCents!=null?badge(money(game.priceCents,game.currency),'orange'):badge('Free to play')}${game.contentRating?badge(game.contentRating,'neutral'):''}</div><div id="player-area" class="section"></div><section class="panel section"><h2>About this game</h2><p class="game-description">${esc(game.description||'The creator has not added a description yet.')}</p>${game.controls?`<h3 class="section">How to play</h3><p>${esc(game.controls)}</p>`:''}</section><div class="section">${notice(premium?'Premium checkout is not active. A listing does not grant a download or ownership.':'Browser games open in an isolated player. Some games require a keyboard and mouse.')}</div>${state.user?`<section class="panel section"><h3>Report a concern</h3>${form('report',select('reason','Reason',[['broken','Game does not work'],['content','Content concern'],['copyright','Copyright concern'],['security','Security concern']])+textArea('description','What happened?','','required maxlength="2000"')+submit('Send Report','btn'),`data-id="${esc(game.id)}"`)}</section>`:''}`};
}
export function authPage(state,path){
 const signup=path==='/signup';const reset=path==='/forgot-password';const resetConfirm=path==='/reset-password';const verify=path==='/verify-email';
 const title=signup?'Join the adventure.':reset?'Reset your password.':resetConfirm?'Choose a new password.':verify?'Verify your email.':'Welcome back.';
 const description=signup?'Create your account to save favorites, collect games, and build your own worlds.':reset?'We will email a reset link if an account matches.':verify?'Confirm your email address to finish setting up your account.':'Your games. Your worlds. All in one place.';
 const hash=new URLSearchParams(location.hash.slice(1));state.authToken=hash.get('token')||'';state.mfaChallenge=hash.get('mfaChallenge')||state.mfaChallenge||'';
 let fields='';let action=signup?'register':reset?'reset-request':resetConfirm?'reset-confirm':verify?'verify-email':state.mfaChallenge?'mfa-login':'login';
 if(verify){fields=state.authToken?submit('Verify Email'):input('email','Email address','email','','required autocomplete="email"')+submit('Send Verification Email');action=state.authToken?'verify-email':'verification-request';}
 else if(state.mfaChallenge&&!signup&&!reset&&!resetConfirm){fields=notice('Enter the six-digit code from your authenticator app.')+input('code','Authentication code','text','','required inputmode="numeric" pattern="[0-9]{6}" autocomplete="one-time-code" maxlength="6"')+submit('Verify & Log In');}
 else{if(signup)fields+=input('displayName','Display name','text','','required maxlength="80" autocomplete="name"')+input('username','Username','text','','required minlength="3" maxlength="30" pattern="[A-Za-z0-9_]+" autocomplete="username"');if(!resetConfirm)fields+=input('email','Email address','email','','required autocomplete="email"');if(!reset)fields+=input('password',resetConfirm?'New password':'Password','password','',`required minlength="12" maxlength="128" autocomplete="${signup||resetConfirm?'new-password':'current-password'}"`);if(signup)fields+='<p class="form-hint">Use at least 12 characters. A unique passphrase works well.</p><label class="checkbox-row"><input type="checkbox" name="terms" required><span>I agree to the <a class="text-link" href="/terms">Terms</a> and have read the <a class="text-link" href="/privacy">Privacy information</a>.</span></label>';fields+=submit(signup?'Create Account':reset?'Send Reset Link':resetConfirm?'Update Password':'Log In');}
 return {html:`<div class="auth-wrap"><section class="panel"><p class="eyebrow">Crate Ship Games</p><h1>${title}</h1><p class="muted">${description}</p>${form(action,fields)}${!reset&&!resetConfirm&&!verify&&!state.mfaChallenge?`<div class="divider">or</div>${state.config?.auth?.google?'<a class="btn full" href="/api/platform/auth/google/start">'+icon('google-logo')+' Continue with Google</a>':'<button class="btn full" disabled>Google sign-in is not configured</button>'}`:''}<div class="auth-links">${link(signup?'/login':'/signup',signup?'Already a member? Log in':'Create an account','')}${link('/forgot-password','Forgot password?','')}</div></section></div>`};
}
export function loginGate(path){return {html:head('Your next adventure starts here.')+empty('Log in to make it yours.','Save favorites, manage your collection, and return to your projects from your account.',link('/login?next='+encodeURIComponent(path),'Log In','btn primary')+' '+link('/signup','Create Account','btn'),'user-circle')};}
export async function collectionPage(state,name){
 const data=await api('/'+name);const rows=listOf(data);state[name]=rows;
 const titles={favorites:'Favorites',library:'My Library',history:'Recently Played',notifications:'Notifications'};
 if(name==='notifications')return {html:head('Notifications','Updates about your account, projects, and submissions.')+(rows.length?`<section class="panel">${rows.map(row=>`<article class="list-row">${icon('bell')}<div><h3>${esc(row.title||'Notification')}</h3><p>${esc(row.message||row.body||'')}</p><small class="muted">${date(row.createdAt)}</small></div>${!row.readAt?btn('read-notification','Mark read','btn small',`data-id="${esc(row.id)}"`):badge('Read','neutral')}</article>`).join('')}</section>`:empty('You’re all caught up.','Account and game updates will appear here.','','bell'))};
 const games=rows.map(r=>r.game||r).filter(g=>g.id||g.slug);return {html:head(titles[name],name==='favorites'?'Keep the worlds you love within reach.':name==='library'?'Your saved games and verified purchases.':'Pick up where you left off.')+(games.length?gameGrid(games):empty(name==='favorites'?'Your favorites belong here.':name==='library'?'Your collection starts with a discovery.':'Your next session is waiting.',name==='favorites'?'Tap the heart on a game to save it.':'Explore the catalog as new games arrive.',link('/games','Explore Games','btn primary'),name==='favorites'?'heart':'game-controller'))};
}
export async function walletPage(state){
 const data=await api('/wallet');const balances=data.balances||{};return {html:head('Rewards','Your balance and its history, securely saved to your account.')+notice('Rewarded ads are currently disabled. Points, credits, and tokens have no cash value, and cannot be purchased or redeemed for cash.')+`<div class="stat-grid section">${[['points','Points'],['credits','Credits'],['tokens','Reward tokens']].map(([key,title])=>`<div class="stat-card"><small>${title}</small><strong>${esc(Number(balances[key]||0).toLocaleString())}</strong><span>Confirmed account balance</span></div>`).join('')}</div><section class="section"><h2>Reward history</h2><div class="section">${data.transactions?.length?table(['Date','Reason','Amount','Type'],data.transactions.map(t=>[esc(date(t.createdAt)),esc(t.reason||t.description),esc(t.amount),esc(t.currency||t.type)])):empty('No rewards recorded yet.','Completed, verified reward activity will appear here.','','receipt')}</div></section>`};
}
export function profilePage(state){const u=state.user;return {html:head('Your Profile','The name other players and creators will see.',link('/settings','Account Settings','btn'))+`<section class="panel">${form('profile',input('displayName','Display name','text',u.displayName||'','required maxlength="80"')+input('username','Username','text',u.username||'','required minlength="3" maxlength="30" pattern="[A-Za-z0-9_]+"')+`<p class="form-hint">Joined ${date(u.createdAt)} · ${esc(u.email)}</p>`+submit('Save Profile'))}</section><div class="section inline-actions">${link('/engine/projects',icon('folder')+' My Projects','btn')}${link('/developer',icon('wrench')+' Developer Dashboard','btn')}${btn('logout',icon('sign-out')+' Log Out','btn ghost')}</div>`};}
export async function settingsPage(state){
 let sessions=[];let sessionError='';let mfaEnabled=false;try{const sessionData=await api('/auth/sessions');sessions=listOf(sessionData,'sessions');mfaEnabled=sessionData.mfaEnabled===true;}catch(e){sessionError=e.message;}
 const prefs=state.user.preferences||{};
 return {html:head('Account Settings','Manage your preferences, security, and active sessions.')+`<div class="page-stack"><section class="panel"><h2>Preferences</h2>${form('preferences',`<label class="setting-row"><span><strong>Reduced motion</strong><p>Keep animations to a minimum.</p></span><input type="checkbox" name="reducedMotion" ${prefs.reducedMotion?'checked':''}></label><label class="setting-row"><span><strong>Optional analytics</strong><p>Allow optional analytics to help improve the game platform.</p></span><input type="checkbox" name="analyticsConsent" ${prefs.analyticsConsent?'checked':''}></label><label class="setting-row"><span><strong>Advertising consent</strong><p>Personalized advertising remains off while the ad service is disabled.</p></span><input type="checkbox" name="advertisingConsent" ${prefs.advertisingConsent?'checked':''}></label>`+submit('Save Preferences'))}</section><section class="panel"><h2>Two-factor authentication</h2><p>Add an authenticator app to protect your account. Owner actions require additional verification.</p><div class="section" id="mfa-enrollment">${mfaEnabled?badge('Authenticator enabled'):btn('mfa-enroll','Set Up Authenticator','btn')}</div></section><section class="panel"><h2>Confirm your identity</h2><p>Recent verification is required for sensitive account actions.</p>${form('reauth',input('password','Password','password','','required autocomplete="current-password"')+input('code','Authenticator code (if enabled)','text','','inputmode="numeric" maxlength="6" autocomplete="one-time-code"')+submit('Verify Identity','btn'))}</section><section class="panel"><div class="panel-title"><h2>Active Sessions</h2>${btn('logout-all','Log Out Everywhere','btn small')}</div>${sessionError?notice(esc(sessionError),true):sessions.length?sessions.map(s=>`<div class="list-row">${icon('device-mobile')}<div><h3>${esc(s.deviceName||s.userAgent||'Browser session')}</h3><p>Last active ${date(s.lastSeenAt||s.createdAt)}</p></div>${s.current?badge('This session'):btn('revoke-session','Revoke','btn small',`data-id="${esc(s.id)}"`)}</div>`).join(''):'<p class="section muted">No session details available.</p>'}</section><section class="panel"><h2>Delete Account</h2><p>Delete your account and personal data according to the retention policy. This cannot be undone. Verify your identity above first.</p>${form('delete-account',input('confirmation','Type DELETE to confirm','text','','required pattern="DELETE" autocomplete="off"')+submit('Delete My Account','btn danger'))}</section></div>`};
}
export async function projectsPage(state){const data=await api('/projects');const projects=listOf(data,'projects');state.projects=projects;return {html:head('My Engine Projects','Your cloud projects. Open the real engine to keep building.',link('/play',icon('wrench')+' Open Engine','btn primary'))+`<section class="panel"><h2>Create a Project</h2>${form('create-project',input('name','Project name','text','','required maxlength="100" placeholder="My next world"')+submit('Create Project'))}</section><section class="section">${projects.length?`<div class="panel">${projects.map(p=>`<article class="list-row">${icon('folder').replace('class="ph','class="row-icon ph')}<div><h3>${esc(p.name||'Untitled project')}</h3><p>Updated ${date(p.updatedAt)} · Revision ${esc(p.revision||1)}</p></div><div class="list-row-actions">${link('/play?project='+encodeURIComponent(p.id),'Open','btn primary small')}${btn('export-project','Export','btn small',`data-id="${esc(p.id)}"`)}${btn('duplicate-project','Duplicate','btn small',`data-id="${esc(p.id)}"`)}${btn('rename-project','Rename','btn small',`data-id="${esc(p.id)}"`)}${btn('delete-project',icon('trash'),'btn small',`aria-label="Delete ${esc(p.name)}" data-id="${esc(p.id)}"`)}</div></article>`).join('')}</div>`:empty('A new world starts with an idea.','Create a project above or explore the engine. Existing browser saves remain in the engine.','','folder')}</section><section class="panel section"><h3>Import a project backup</h3>${form('import-project',input('name','Project name','text','','required maxlength="100"')+'<label>Crate project file<input type="file" name="projectFile" accept=".crate,.json,application/json" required></label>'+submit('Import Backup'))}</section>`};}
export function creatorsPage(){return {html:head('A home for your next game.','Build today. Help shape what comes next.')+`<section class="panel"><p class="eyebrow">Creator access · Coming soon</p><h2>Your ideas deserve a world.</h2><p>The creator program is being prepared for browser games and premium downloadable releases. Join the waitlist to hear when submissions open.</p><div class="inline-actions section">${link('/play','Open the Game Engine','btn primary')}${link('/developer','Developer Dashboard','btn')}${link('/developers/docs','Read the Guide','btn')}</div></section><section class="panel section" id="waitlist"><h2>Join the Creator Waitlist</h2><p>Get updates about early access and creator tools.</p>${form('waitlist',input('email','Email address','email','','required autocomplete="email"')+select('interest','What would you like to create?',[['web','Browser games'],['premium','Premium downloadable games'],['both','Both']])+'<label class="checkbox-row"><input type="checkbox" name="consent" required><span>Send creator access updates to my verified account email.</span></label>'+submit('Join the Waitlist'))}</section>`,full:creatorSections()};}



