import {api} from './api.mjs';
import {esc,head,notice,link,btn,feedback,money,badge} from './ui.mjs';
export async function paymentsPage(state){
 const commerce=state.config.commerce||{};
 if(!commerce.connected)return {html:head('Sell your games','Stripe setup is in progress.')+notice('Game sales have not opened yet. Your game drafts and free games are available as usual.')};
 if(commerce.mode==='test'&&!state.user?.roles?.includes('OWNER'))return {html:head('Sell your games')+notice('Seller setup opens after the owner finishes the sandbox integration.')};
 const data=await api('/seller/stripe'),account=data.account,agreements=await api('/seller/agreements');
 return {html:head('Game sales & payments','Manage your seller verification through Stripe.')+`<div class="page-stack">${data.mode==='test'?notice('Owner sandbox · use Stripe test information only. Test payments never unlock real games or create real earnings.'):''}<section class="panel"><h2>Your sale share</h2><p>You receive 80% of each game sale. CrateShip receives 20% and pays Stripe processing fees from its share. Refunds reverse the sale share. This launch supports USD browser games and US adult sellers.</p><p class="section">${link('/creator-agreement','Creator agreement','text-link')} · ${link('/refund-policy','Refund policy','text-link')} · ${link('/payout-policy','Payout information','text-link')}</p></section><section class="panel"><h2>Stripe seller account</h2>${account?`<p>${badge(account.chargesEnabled&&account.payoutsEnabled?'Verified for payments':'Verification incomplete')}</p><p class="section">${account.requirementsDue?esc(account.requirementsDue)+' verification requirements remain.':'Check Stripe for account and payout requirements.'}</p>`:'<p>Connect a seller account to receive your game sale share. Stripe collects identity and bank details directly.</p>'}<form class="form section" data-form="stripe-onboard"><label class="checkbox-row"><input type="checkbox" name="adultAndUSSeller" required><span>I am at least 18 and am setting up a US seller account.</span></label><button class="btn primary" type="submit">${account?'Continue Stripe setup':'Set up with Stripe'}</button>${feedback()}</form>${btn('refresh-payments','Refresh verification','btn small')}</section><section class="panel"><h2>Your assigned sales agreements</h2>${agreements.agreements.length?agreements.agreements.map(a=>`<article class="section"><h3>${esc(a.name)} · Version ${esc(a.version)}</h3><p>Game sales: ${esc(a.terms.premium_sales.creatorBps/100)}% creator / ${esc(a.terms.premium_sales.platformBps/100)}% platform. Currency ${esc(a.currency)}. ${esc(a.public_notes)}</p><p>Payout schedule: ${esc(a.payment_schedule)}. Policy version: ${esc(agreements.policyVersion||'Not finalized')}.</p>${a.accepted?badge('Accepted'):data.mode==='live'?`<form class="form section" data-form="seller-accept" data-agreement="${esc(a.id)}" data-policy="${esc(agreements.policyVersion)}"><label class="checkbox-row"><input type="checkbox" name="accepted" required><span>I have read the ${link('/creator-agreement','creator agreement','text-link')}, refund and payout policies, and accept this assigned agreement and policy version.</span></label><button class="btn" type="submit">Accept this sales agreement</button>${feedback()}</form>`:notice('Agreement acceptance is disabled in the sandbox.')}</article>`).join(''):'<p class="section">No agreement is assigned. Uploading a game does not create a sales agreement.</p>'}</section></div>`};
}
export async function checkoutReturnPage(state){
 const orderId=new URLSearchParams(location.search).get('order');if(!orderId)return {html:head('Checkout')+notice('No order was specified.',true)};
 const data=await api('/checkout/orders/'+encodeURIComponent(orderId)),order=data.order;
 const description=order.mode==='test'?'Sandbox result · no real payment or license.':data.licensed?'Your verified purchase is ready.':['refunded','disputed'].includes(order.status)?'Game access is suspended for this order.':'We are waiting for Stripe to verify the payment.';
 return {html:head(order.status==='paid'?'Checkout complete':'Checkout status',description)+`<section class="panel"><p>${badge(order.status)} ${esc(money(order.totalMinor,order.currency))}</p><div class="inline-actions section">${data.licensed?link('/game/'+encodeURIComponent(order.gameSlug),'Open your game','btn primary')+link('/library','My library','btn'):btn('refresh-payments','Check status','btn')+link('/game/'+encodeURIComponent(order.gameSlug),'Back to the game','btn')}</div>${order.mode==='test'?notice('Test purchases stay separate from player licenses and creator balances.'):''}</section>`};
}
export async function stripeOwnerPage(){
 const data=await api('/owner/stripe');return {html:head('Stripe setup','Checkout and creator sales readiness.')+`<section class="panel"><p>Provider: ${badge(data.connected?'Connected':'Not connected')} Mode: ${badge(data.mode||'Not configured')}</p><ul class="steps-list section"><li>Webhook verification: ${data.webhookConfigured?'Configured':'Required'}</li><li>Licensed game hosting: ${data.deliveryReady?'Configured':'Required'}</li><li>Final sales policy: ${esc(data.policyVersion||'Required')}</li><li>Live release approval: ${data.checkoutEnabled?'Configured; payment flags also required':'Pending'}</li></ul><p>Creator sales use an 80% creator / 20% platform split. Processor fees are paid by the platform. Owner-owned games remain 100% platform revenue before costs.</p><div class="inline-actions section">${link('/developer/payments','Seller setup','btn')}${link('/owners-portal/settings','Feature controls','btn')}${link('/games/premium','Premium catalog','btn')}</div></section>`};
}
