export const esc = value => String(value ?? '').replace(/[&<>"']/g, c => ({'&':'&amp;','<':'&lt;','>':'&gt;','"':'&quot;',"'":'&#39;'}[c]));
export const icon = (name, cls = '') => `<i class="${name.endsWith('-fill')?'ph-fill':'ph'} ph-${name.replace(/-fill$/,'')} ${cls}" aria-hidden="true"></i>`;
export const tool = (action, name, title, cls = '', extra = '') => `<button type="button" class="icon-button ${cls}" data-action="${action}" title="${esc(title)}" aria-label="${esc(title)}" ${extra}>${icon(name)}</button>`;
const option = (value, label, current) => `<option value="${esc(value)}" ${value===current?'selected':''}>${esc(label)}</option>`;
export const bytes = value => Number(value)>1048576 ? `${(Number(value)/1048576).toFixed(1)} MB` : `${Math.ceil(Number(value||0)/1024)} KB`;
export const typeIcons = {box:'cube',sphere:'circle',cylinder:'cylinder',capsule:'pill',plane:'square',directionalLight:'sun',pointLight:'lightbulb',camera:'video-camera',model:'cube-transparent',empty:'circles-four'};
export const primitiveTypes = [['box','Cube'],['sphere','Sphere'],['cylinder','Cylinder'],['capsule','Capsule'],['plane','Plane'],['directionalLight','Sun light'],['pointLight','Point light'],['camera','Camera'],['empty','Empty object']];

export function layout() {
 return `<header class="editor-header">
   <a class="engine-brand" href="/" title="CrateShip Games home"><img src="/platform/media/crate-mark.png" alt=""><span>CRATE<span class="engine-word">ENGINE</span></span></a>
   <a class="games-link" href="/games" aria-label="Back to games">${icon('game-controller')}<span>Games</span></a>
   <span class="header-separator"></span><button class="project-name" data-action="rename" title="Rename project"><span id="project-name">Opening project</span>${icon('caret-down')}</button>
   <span id="save-state" class="save-state">Initializing</span>
   <div class="header-actions"><button class="text-button" data-action="open" aria-label="Open">${icon('folder-open')}<span>Open</span></button><button class="text-button" data-action="save" aria-label="Save">${icon('floppy-disk')}<span>Save</span></button><button class="text-button" data-action="import" aria-label="Import">${icon('download-simple')}<span>Import</span></button><button class="primary-button compact" data-action="export" aria-label="Export">${icon('export')}<span>Export</span></button><a class="account-button" href="/profile" title="Account" aria-label="Account">${icon('user-circle')}</a></div>
 </header>
 <div class="editor-toolbar"><div class="toolbar-group"><button class="text-button" data-action="new">${icon('file-plus')}<span>New project</span></button><button class="text-button" data-action="demo" aria-label="Build side-view game demo">${icon('game-controller')}<span>Build demo</span></button><span class="toolbar-divider"></span>${tool('undo','arrow-u-up-left','Undo (Ctrl Z)')}${tool('redo','arrow-u-up-right','Redo (Ctrl Shift Z)')}</div>
   <div class="play-controls"><button class="play-button" id="play-button" data-action="play">${icon('play-fill')}<span>Play</span></button><button class="stop-button" data-action="stop" title="Stop preview (Escape)" disabled>${icon('stop-fill')}<span>Stop</span></button></div>
   <div class="toolbar-group toolbar-right"><button class="text-button build-ai-button" data-action="build-with-ai" aria-label="Build with AI">${icon('sparkle')}<span>Build with AI</span></button><button class="text-button ai-apps-button" data-action="ai-apps" aria-label="AI apps">${icon('robot')}<span>AI apps</span></button><button class="text-button world-builder-button" data-action="world-builder" aria-label="World builder">${icon('sparkle')}<span>World builder</span></button><button class="text-button" data-action="connections" aria-label="Connections">${icon('plugs-connected')}<span>Connections</span></button><button class="icon-button" data-action="help" title="Keyboard shortcuts" aria-label="Keyboard shortcuts">${icon('question')}</button></div>
 </div>
 <nav class="mobile-pane-tabs" aria-label="Editor panels"><button data-pane="scene" aria-pressed="false">${icon('list-dashes')} Scene</button><button data-pane="viewport" aria-pressed="true">${icon('cube')} Viewport</button><button data-pane="inspector" aria-pressed="false">${icon('sliders-horizontal')} Inspector</button><button data-pane="assets" aria-pressed="false">${icon('folder')} Assets</button></nav>
 <main class="editor-workspace" data-pane="viewport">
   <aside class="scene-panel editor-panel"><div class="panel-title"><h2>${icon('stack')} Scene</h2><button class="icon-button" data-action="add" title="Add object" aria-label="Add object">${icon('plus')}</button></div><label class="panel-search">${icon('magnifying-glass')}<input id="hierarchy-search" placeholder="Find an object…" aria-label="Find a scene object"><kbd>/</kbd></label><div class="scene-root">${icon('globe-hemisphere-west')}<span id="scene-root-name">Scene</span><span id="entity-count">0</span></div><div id="hierarchy" class="hierarchy" role="tree" aria-label="Scene hierarchy"></div><div class="scene-bottom"><button class="wide-button" data-action="add">${icon('plus')} Add object</button><button class="text-button" data-action="scene-settings">${icon('gear-six')} Scene settings</button></div></aside>
   <section class="viewport-panel"><div class="viewport-toolbar"><div class="viewport-title">${icon('cube')} Scene view <span class="viewport-badge" id="mode-label">EDIT</span></div><div class="transform-tools" role="group" aria-label="Transform tool">${tool('tool:translate','arrows-out-cardinal','Move (W)','active','aria-pressed="true"')}${tool('tool:rotate','arrow-clockwise','Rotate (E)','','aria-pressed="false"')}${tool('tool:scale','arrows-out-simple','Scale (R)','','aria-pressed="false"')}</div><button class="space-button" data-action="space" title="Toggle world or local axes">${icon('globe')}<span id="space-label">World</span></button><div class="viewport-right">${tool('frame','frame-corners','Frame selection (F)')}${tool('fullscreen','corners-out','Expand viewport')}</div></div>
    <div class="canvas-wrap" id="canvas-wrap"><canvas id="editor-canvas" tabindex="0" aria-label="Interactive 3D scene viewport"></canvas><div id="viewport-loading" class="viewport-loading"><span class="loader-line"></span><b>Opening your workspace</b><span>Preparing the 3D renderer</span></div><div class="viewport-corner"><span class="view-pill">Perspective</span><span class="view-pill">Lit</span></div><div class="viewport-guidance" id="viewport-guidance"><span>Orbit <kbd>Drag</kbd></span><span>Pan <kbd>Right drag</kbd></span><span>Zoom <kbd>Pinch / scroll</kbd></span></div><div id="runtime-hud" class="runtime-hud" hidden><span>Playing your Player Controller</span><small>WASD / touch · Move &nbsp; Space · Jump</small><small>Press Stop to select and edit other objects.</small></div><div class="drop-target" id="drop-target" hidden>${icon('download-simple')}<b>Drop your assets into the scene</b><span>GLB models and Crate projects</span></div></div>
   </section>
   <aside class="inspector-panel editor-panel"><div class="panel-title"><h2>${icon('sliders-horizontal')} Inspector</h2><span class="tiny-label" id="inspector-type">SCENE</span></div><div id="inspector" class="inspector-scroll"></div></aside>
   <section class="assets-panel editor-panel"><div class="asset-toolbar"><div class="bottom-tabs" role="tablist" aria-label="Project resources"><button class="active" role="tab" aria-selected="true" data-bottom-tab="assets">${icon('folder')} Assets <span id="asset-count">0</span></button><button role="tab" aria-selected="false" data-bottom-tab="console">${icon('terminal-window')} Console <span id="log-count">0</span></button></div><div class="asset-toolbar-actions"><button class="text-button" data-action="import" aria-label="Import">${icon('upload-simple')} Import files</button><button class="text-button" data-action="connections" aria-label="Connections">${icon('plugs-connected')} Blender & models</button></div></div><div id="assets-view" class="assets-view"><nav class="asset-sources" aria-label="Asset source"><button data-asset-source="project" class="active">${icon('folder-open')} My project</button><button data-asset-source="starter">${icon('star')} Starter library <span>3 characters</span></button></nav><div class="asset-main"><div class="asset-filter"><label>${icon('magnifying-glass')}<input id="asset-search" placeholder="Search assets…" aria-label="Search assets"></label><span id="asset-source-note">Your imports stay with your project</span></div><div class="asset-library-tools"><select id="asset-category" aria-label="Asset category" hidden><option value="">All categories</option></select><span id="asset-library-count" role="status"></span><button class="text-button" id="asset-more" data-action="more-assets" hidden>Show more</button></div><div id="asset-grid" class="asset-grid"></div></div></div><div id="console-view" class="console-view" hidden><div id="console-list" role="log" aria-label="Editor messages"></div><button class="text-button" data-action="clear-log">Clear console</button></div></section>
 </main><footer class="editor-status"><span><i class="status-dot"></i><span id="editor-status-text">Starting renderer</span></span><span id="stats">—</span><span class="status-shortcuts"><kbd>F</kbd> Frame selection <kbd>Ctrl S</kbd> Save</span><span class="status-version">Crate Engine · Project v4</span></footer>
 <input type="file" id="import-files" multiple accept=".crate,.json,.glb" hidden>
 <div id="editor-toasts" role="status" aria-live="polite"></div><div id="dialog-root"></div>`;
}

export function hierarchy(project, selectedId, filter = '') {
 const entities = project?.entities || [], byId = new Map(entities.map(e=>[e.id,e]));
 const depth = e => {let d=0,p=e.parentId,seen=new Set([e.id]);while(p&&byId.has(p)&&!seen.has(p)){seen.add(p);d++;p=byId.get(p).parentId;}return Math.min(d,8);};
 const rows = entities.filter(e=>!filter||String(e.name).toLowerCase().includes(filter.toLowerCase()));
 return rows.length ? rows.map(e=>`<div class="tree-row ${selectedId===e.id?'selected':''}" role="treeitem" aria-selected="${selectedId===e.id}" style="--depth:${depth(e)}"><button class="tree-select" data-select="${esc(e.id)}">${icon(typeIcons[e.type]||'cube')}<span>${esc(e.name)}</span></button><button class="tree-visibility" data-visible="${esc(e.id)}" title="${e.visible===false?'Show':'Hide'} object" aria-label="${e.visible===false?'Show':'Hide'} ${esc(e.name)}">${icon(e.visible===false?'eye-slash':'eye')}</button></div>`).join('') : `<div class="panel-empty">${icon('stack')}<p>${filter?'No matching objects':'A blank canvas for your next idea.'}</p>${filter?'':'<button class="text-button" data-action="add">Add your first object</button>'}</div>`;
}
const input = (name,label,value,type='text',extra='') => `<label class="field"><span>${esc(label)}</span><input name="${name}" type="${type}" value="${esc(value)}" ${type==='number'?extra.replace(/step="[^"]*"/g,'step="any"'):extra}></label>`;
const select = (name,label,values,current) => `<label class="field"><span>${esc(label)}</span><select name="${name}">${values.map(([v,l])=>option(v,l,current)).join('')}</select></label>`;
const vector = (key,label,value) => `<div class="vector-field"><span>${label}</span><div>${['X','Y','Z'].map((axis,i)=>`<label class="axis-${axis.toLowerCase()}"><b>${axis}</b><input aria-label="${label} ${axis}" name="${key}.${i}" type="number" step="any" value="${esc(value?.[i]??(key==='scale'?1:0))}"></label>`).join('')}</div></div>`;
function componentFields(name,value) {
 if(name==='rigidbody')return select('components.rigidbody.type','Body type',[['static','Static'],['dynamic','Dynamic']],value.type)+input('components.rigidbody.mass','Mass',value.mass??1,'number','min="0.001" step="0.1"')+input('components.rigidbody.friction','Friction',value.friction??0.7,'number','min="0" max="10" step="0.1"')+input('components.rigidbody.restitution','Bounce',value.restitution??0.2,'number','min="0" max="1" step="0.05"')+select('components.rigidbody.collider','Collision shape',[['auto','Automatic (outline for drawn shapes)'],['box','Box (fast, stable)'],['shape','Follow the outline']],['box','shape'].includes(value.collider)?value.collider:'auto');
 if(name==='spin')return input('components.spin.speed','Speed',value.speed??30,'number','min="-720" max="720" step="1"');
 if(name==='collectible')return input('components.collectible.value','Value',value.value??1,'number','min="0" step="1"');
 if(name==='player')return input('components.player.speed','Move speed',value.speed??5,'number','min="0.1" max="50" step="0.1"')+input('components.player.jump','Jump strength',value.jump??6,'number','min="0" max="30" step="0.1"');
 if(name==='goal')return input('components.goal.message','Win message',value.message||'Level complete!','text','maxlength="120"')+'<p class="field-help">The player wins when touching this object.</p>';
 if(name==='hazard')return '<p class="field-help">Touching this costs a life and returns the player to the last checkpoint.</p>';
 if(name==='checkpoint')return '<p class="field-help">Touching this saves where the player respawns.</p>';
 if(name==='mover')return vector('components.mover.offset','Travel',value.offset||[0,2,0])+input('components.mover.period','Round trip (seconds)',value.period??4,'number','min="0.2" max="120" step="0.1"')+'<p class="field-help">Moves back and forth along Travel and carries a standing player.</p>';
 if(name==='water')return input('components.water.waveHeight','Wave height (m)',value.waveHeight??.6,'number','min="0" max="5" step="0.05"')+input('components.water.waveLength','Wave length (m)',value.waveLength??24,'number','min="4" max="200" step="1"')+input('components.water.speed','Wave speed',value.speed??1,'number','min="0" max="5" step="0.1"')+input('components.water.choppiness','Choppiness',value.choppiness??.5,'number','min="0" max="1" step="0.05"')+input('components.water.opacity','Opacity',value.opacity??.86,'number','min="0.3" max="1" step="0.02"')+input('components.water.deepColor','Deep water colour',value.deepColor||'#0a4d6e','color')+select('components.water.foam','Wave foam',[['true','On'],['false','Off']],String(value.foam!==false))+'<p class="field-help">Animated Gerstner waves. The object colour is the shallow water colour.</p>';
 if(name==='animation')return input('components.animation.clip','Clip name',value.clip||'','text','maxlength="120" placeholder="First available"')+select('components.animation.autoplay','Autoplay',[['true','Enabled'],['false','Disabled']],String(value.autoplay!==false))+input('components.animation.speed','Playback speed',value.speed??1,'number','min="0.01" max="5" step="0.1"');
 return '<p>Preserved project component</p>';
}
export function inspector(entity, project) {
 if (!entity) return `<div class="inspector-intro">${icon('globe-hemisphere-west')}<h3>Your scene, your rules.</h3><p>Select an object to adjust its transform, material, and behavior.</p></div><form id="scene-settings-form"><section class="inspector-section"><h3>${icon('sun-horizon')} Scene environment</h3>${input('background','Background',project?.settings?.background||'#18251e','color')}${input('ambientIntensity','Ambient light',project?.settings?.ambientIntensity??0.8,'number','min="0" max="10" step="0.1"')}${input('exposure','Exposure',project?.settings?.exposure??1.15,'number','min="0.1" max="5" step="0.05"')}${input('fogDensity','Fog density',project?.settings?.fogDensity??0,'number','min="0" max="0.2" step="0.005"')}${input('gravity','Gravity',project?.settings?.gravity??-9.81,'number','min="-100" max="100" step="0.1"')}${select('quality','Render quality',[['low','Low'],['balanced','Balanced'],['high','High · Ambient occlusion']],project?.settings?.quality||'balanced')}${select('shadows','Shadows',[['true','Enabled'],['false','Disabled']],String(project?.settings?.shadows!==false))}</section><section class="inspector-section"><h3>${icon('flag-banner')} Level rules</h3>${input('lives','Lives (0 = unlimited)',project?.settings?.lives??0,'number','min="0" max="99" step="1"')}${input('killY','Fall-out height',project?.settings?.killY??-30,'number','min="-10000" max="10000" step="1"')}<p class="field-help">Players who fall below this height respawn.</p><button class="wide-button" type="submit">Apply environment</button></section></form><div class="inspector-note">${icon('cursor-click')} Pick in the viewport or the scene hierarchy. All changes can be undone.</div>`;
 const components = entity.components || {};
 return `<form id="entity-form" data-id="${esc(entity.id)}"><section class="inspector-identity">${icon(typeIcons[entity.type]||'cube')}<input name="name" aria-label="Object name" value="${esc(entity.name)}" maxlength="120"><button class="icon-button" type="button" data-action="duplicate" title="Duplicate object" aria-label="Duplicate object">${icon('copy')}</button></section><section class="inspector-section"><h3>${icon('arrows-out-cardinal')} Transform</h3>${vector('position','Position',entity.position)}${vector('rotation','Rotation °',entity.rotation)}${vector('scale','Scale',entity.scale)}${select('parentId','Parent',[['','Scene root'],...(project.entities||[]).filter(e=>e.id!==entity.id).map(e=>[e.id,e.name])],entity.parentId||'')}</section>
 <section class="inspector-section">${entity.type.endsWith('Light')?`<h3>${icon('sun')} Light</h3>${input('light.color','Color',entity.light?.color||'#fff1dd','color')}${input('light.intensity','Intensity',entity.light?.intensity??3,'number','min="0" max="1000" step="0.1"')}${entity.type==='pointLight'?input('light.distance','Distance',entity.light?.distance??30,'number','min="0" step="1"'):''}`:['empty','camera'].includes(entity.type)?`<h3>${icon('info')} ${entity.type==='empty'?'Object group':'Camera'}</h3><p class="field-help">${entity.type==='empty'?'Group scene objects under this parent to move them together.':'The first visible scene camera sets the game view. Position and rotate it in the scene.'}</p>`:entity.type==='model'?`<h3>${icon('paint-bucket')} Imported materials</h3><p class="field-help">Original model materials and textures are preserved.</p>`:`<h3>${icon('paint-bucket')} Material</h3>${input('material.color','Base color',entity.material?.color||'#df8b49','color')}${input('material.metalness','Metalness',entity.material?.metalness??0,'range','min="0" max="1" step="0.01"')}${input('material.roughness','Roughness',entity.material?.roughness??0.7,'range','min="0" max="1" step="0.01"')}`}</section>
 <section class="inspector-section"><h3>${icon('puzzle-piece')} Components</h3>${Object.entries(components).map(([name,value])=>`<div class="component"><div class="component-heading"><b>${esc({rigidbody:'Rigid body',spin:'Spin',collectible:'Collectible',player:'Player controller',animation:'Animation',goal:'Goal',hazard:'Hazard',checkpoint:'Checkpoint',mover:'Moving platform',water:'Water'}[name]||name)}</b><button type="button" class="icon-button" data-remove-component="${esc(name)}" title="Remove component" aria-label="Remove ${esc(name)}">${icon('x')}</button></div>${componentFields(name,value)}</div>`).join('')}<button class="wide-button" type="button" data-action="component">${icon('plus')} Add component</button></section><section class="inspector-section object-actions"><button class="text-button danger" type="button" data-action="remove">${icon('trash')} Delete object</button><span class="object-id">${esc(entity.id.slice(0,8))}</span></section></form>`;
}

export function assetCards(items, source='project', query='') {
 const visible=items.filter(a=>!query||`${a.name} ${a.cat||''}`.toLowerCase().includes(query.toLowerCase()));
 if(!visible.length)return `<div class="asset-empty">${icon(source!=='project'?'cube-transparent':'upload-simple')}<div><b>${query?'No matching assets':source!=='project'?'Catalog unavailable':'Make this world your own'}</b><p>${query?'Try another name.':source!=='project'?'This model library could not be loaded. Import your own GLB files.':'Import a model, bring a scene from Blender, or start with a primitive.'}</p></div>${source==='project'&&!query?'<button class="primary-button compact" data-action="import" aria-label="Import">Import assets</button>':''}</div>`;
 return visible.map(a=>`<button class="asset-card" data-asset="${esc(source!=='project'?a.file:a.id)}" data-source="${source}" title="${'Add'} ${esc(a.name)}"><div class="asset-preview">${source!=='project'&&typeof a.thumb==='string'&&/^\/starter-library\/thumbs\/[a-z0-9_]+\.webp$/.test(a.thumb)?`<img src="${esc(a.thumb)}" alt="" loading="lazy" decoding="async">`:icon(source!=='project'?'cube-transparent':a.mime?.startsWith('image/')?'image':'cube')}<span>${esc(source!=='project'?'GLB':a.source==='blender'?'BLENDER':'ASSET')}</span></div><b>${esc(a.name)}</b><small>${esc(source!=='project'?(a.cat||'Catalog'):bytes(a.size))}</small></button>`).join('');
}

export function dialog(title,body,cls='') {
 return `<div class="dialog-backdrop"><section class="editor-dialog ${cls}" role="dialog" aria-modal="true" aria-labelledby="dialog-title"><header><div><span class="eyebrow">CRATE ENGINE</span><h2 id="dialog-title">${esc(title)}</h2></div><button class="icon-button" data-action="close-dialog" title="Close" aria-label="Close">${icon('x')}</button></header>${body}</section></div>`;
}
export function connectionsShell() {
 return `<div class="connection-tabs"><button class="active" data-connection-tab="models">${icon('plugs-connected')} Model providers</button><button data-connection-tab="blender">${icon('cube-transparent')} Blender</button></div><div id="connection-content"><p class="loading-copy">Loading your connections…</p></div><details class="connection-form-details"><summary>${icon('cube-transparent')} Create 3D assets with your own API</summary><p class="dialog-lead">Generate a model with your own provider account, download its GLB, then import it here—even from your phone.</p><p class="field-help">TRELLIS.2 and Hunyuan3D are optional external generation workflows. Direct generation inside this editor is not connected yet. Any generation charges belong to your provider account; Crate Ship does not supply credits.</p><p><a href="https://fal.ai/models/fal-ai/trellis-2/api" target="_blank" rel="noopener noreferrer">TRELLIS.2 API on fal ↗</a></p><p><a href="https://fal.ai/models/fal-ai/hunyuan-3d/v3.1/pro/image-to-3d" target="_blank" rel="noopener noreferrer">Hunyuan3D API on fal ↗</a></p><p class="field-help">Import a self-contained GLB up to 32 MB. For phones, start with smaller meshes and textures and use Low or Balanced quality. Blender and its local bridge run on a desktop computer.</p><button class="wide-button" data-action="import">Import generated GLB</button></details>`;
}
export function modelConnections(data={}) {
 const items=data.items||[];
 return `<p class="dialog-lead">Your models. Your API keys. Your provider bills your account for requests you choose to send. Crate Ship supplies no paid AI credits.</p><p class="field-help">Manual editing, local saving and importing your own models need no AI key. Provider prices and spending limits are managed in your provider account.</p><div id="connection-state" class="inline-note">${data.enabled?'Provider requests are enabled.':'Provider requests are currently disabled. Saved connections will become usable when the service is enabled.'}</div><div class="connection-list">${items.length?items.map(item=>`<article class="connection-row"><span class="connection-icon">${icon('plugs-connected')}</span><div><b>${esc(item.label||item.provider)}</b><small>${esc(item.provider)} · ${esc(item.model)} · ${esc(item.keyHint||'Key saved')}</small><small>${item.lastTestStatus?'Last test: '+esc(item.lastTestStatus):'Not tested yet'}</small></div><button class="text-button" data-test-connection="${esc(item.id)}" ${data.enabled?'':'disabled'}>Test</button><button class="icon-button danger" data-delete-connection="${esc(item.id)}" title="Remove connection" aria-label="Remove connection">${icon('trash')}</button></article>`).join(''):'<div class="connection-empty">No model connections yet. Add your own provider below.</div>'}</div>
 <details class="connection-form-details" ${items.length?'':'open'}><summary>${icon('plus')} Add a model connection</summary><form id="model-connection-form" class="dialog-form"><div class="form-two">${select('provider','Provider',[['openai','OpenAI'],['anthropic','Anthropic'],['openrouter','OpenRouter']],'openai')}${input('label','Connection name','','text','required maxlength="80" placeholder="My model account"')}</div>${input('model','Model ID','','text','required maxlength="120" placeholder="Enter the provider’s exact model ID"')}${input('apiKey','API key','','password','required autocomplete="off" spellcheck="false"')}<p class="field-help">Keys are sent securely to your account connection service and never stored in this browser.</p><button class="primary-button" type="submit">Save connection</button></form></details>
 ${items.length?`<form id="model-proposal-form" class="dialog-form proposal-form"><h3>${icon('sparkle')} Build with AI</h3><p class="field-help">Tell your AI what to build: a whole game or one change. It draws its own art and builds straight into this scene. Undo reverses any build.</p>${select('connectionId','Connection',items.map(i=>[i.id,i.label||i.provider]),items[0].id)}<label class="field stacked"><span>What should it build?</span><textarea name="prompt" required maxlength="8000" rows="5" placeholder="Build a 2D side-scrolling platformer about a cat collecting stars, with spikes, moving platforms, a checkpoint and a goal."></textarea></label><label class="checkbox-field"><input type="checkbox" name="replaceScene"><span>Start from an empty scene (removes the current objects first)</span></label>${input('maxOutputTokens','Maximum output tokens',16384,'number','min="128" max="32768" step="128" required')}<label class="checkbox-field"><input type="checkbox" name="confirmProviderUsage" required><span>Send this scene summary to my provider and use my provider account.</span></label><button class="primary-button" ${data.enabled?'':'disabled'} type="submit">${icon('sparkle')} Build it</button><div id="proposal-result"></div></form>`:'<p class="field-help">Add a model connection above to get a Build with AI prompt box.'}<p class="field-help">Using a Claude or ChatGPT subscription instead of an API key? Turn on <b>AI apps</b> in the toolbar and type your request in that app. It builds here the same way.</p>`;
}
