import test from 'node:test';
import assert from 'node:assert/strict';
import http from 'node:http';
import { randomUUID } from 'node:crypto';
import { spawn } from 'node:child_process';
import { fileURLToPath } from 'node:url';
import { createEditorBridge } from './bridge.mjs';
import { callEditor } from './mcp-server.mjs';
import { validArguments, validResult } from './contracts.mjs';
import { createEditorMcpClient } from '../../engine/editor/mcp-client.mjs';
import { sceneContext } from '../../engine/editor/scene-context.mjs';
import { newProject } from '../../engine/core/schema.mjs';
import { compileWorldRecipe } from '../../engine/core/procedural.mjs';
import { ProjectStore } from '../../engine/core/project-store.mjs';

const origin='http://127.0.0.1:4173',recipe={version:1,seed:'local test',operations:[{op:'grid',entity:{type:'box',name:'Block'},counts:[2,3],spacing:[2,2],origin:[0,0,0]}]};
const delay=ms=>new Promise(resolve=>setTimeout(resolve,ms));
async function fixture(t,options={}){
 const bridge=createEditorBridge({port:0,origin,...options}),address=await bridge.listen();t.after(()=>bridge.close());const base=`http://127.0.0.1:${address.port}`;
 const request=(path,{browser=false,method='GET',body,headers={}}={})=>fetch(base+path,{method,headers:{authorization:`Bearer ${browser?bridge.editorToken:bridge.token}`,...(browser?{origin}:{}),...(body!==undefined?{'content-type':'application/json'}:{}),...headers},body:body===undefined?undefined:typeof body==='string'?body:JSON.stringify(body)});
 const connect=async(allowWrites=false,projectId='project-one')=>{const r=await request('/editor/connect',{browser:true,method:'POST',body:{projectId,allowWrites}});assert.equal(r.status,201);return r.json();};
 const submit=(session,command='get_scene',args={},requestId=randomUUID())=>request('/commands',{method:'POST',body:{requestId,sessionId:session.sessionId,projectId:session.projectId,command,arguments:args}});
 const poll=session=>request(`/editor/sessions/${session.sessionId}/commands`,{browser:true});
 const result=(session,commandId,value)=>request(`/editor/sessions/${session.sessionId}/results`,{browser:true,method:'POST',body:{commandId,projectId:session.projectId,result:value}});
 return {bridge,address,base,request,connect,submit,poll,result};
}
function scene(projectId='project-one'){const p=newProject('Test');p.id=projectId;return sceneContext(p);}
async function stage(f,session){const q=await(await f.submit(session,'preview_world',{recipe})).json();const batch=await(await f.poll(session)).json();assert.equal(batch.commands[0].id,q.id);const compiled=compileWorldRecipe(recipe,newProject());const preview={previewId:randomUUID(),summary:compiled.summary,entities:compiled.entities};assert.equal((await f.result(session,q.id,preview)).status,200);return preview;}

test('bridge binds loopback with separate random browser and MCP capabilities',async t=>{const f=await fixture(t),other=await fixture(t);assert.equal(f.address.address,'127.0.0.1');for(const token of[f.bridge.token,f.bridge.editorToken])assert.match(token,/^[A-Za-z0-9_-]{43}$/);assert.notEqual(f.bridge.token,f.bridge.editorToken);assert.notEqual(f.bridge.token,other.bridge.token);assert.equal((await(await f.request('/status')).json()).session,null);});
test('MCP capability cannot connect or grant writes even with spoofed allowed Origin',async t=>{const f=await fixture(t);assert.equal((await f.request('/editor/connect',{method:'POST',headers:{origin},body:{projectId:'project-one',allowWrites:true}})).status,403);const s=await f.connect();assert.equal((await f.request(`/editor/sessions/${s.sessionId}/permissions`,{method:'POST',headers:{origin},body:{projectId:s.projectId,allowWrites:true}})).status,403);});
test('browser capability cannot submit native commands',async t=>{const f=await fixture(t);await f.connect(true);assert.equal((await f.request('/commands',{browser:true,method:'POST',body:{}})).status,403);});
for(const [name,headers,status]of[['no token',{authorization:''},401],['foreign Origin',{origin:'https://evil.test'},403],['opaque Origin',{origin:'null'},403],['bad token',{authorization:'Bearer no'},401]])test(`rejects ${name}`,async t=>{const f=await fixture(t);assert.equal((await f.request('/status',{headers})).status,status);});
test('strict Host prevents DNS rebinding; paths cannot contain query credentials',async t=>{const f=await fixture(t);const status=await new Promise((resolve,reject)=>{const req=http.request(f.base+'/status',{headers:{host:'evil.test',authorization:`Bearer ${f.bridge.token}`}},res=>{res.resume();resolve(res.statusCode);});req.on('error',reject);req.end();});assert.equal(status,403);assert.equal((await f.request('/status?token=x')).status,403);});
test('only configured browser may preflight allowed methods and headers',async t=>{const f=await fixture(t);const r=await f.request('/editor/connect',{method:'OPTIONS',headers:{origin,'access-control-request-method':'POST','access-control-request-headers':'authorization,content-type'}});assert.equal(r.status,204);assert.equal(r.headers.get('access-control-allow-origin'),origin);assert.equal(r.headers.get('access-control-allow-credentials'),null);assert.equal((await f.request('/editor/connect',{method:'OPTIONS',headers:{origin,'access-control-request-method':'POST','access-control-request-headers':'x-execute'}})).status,403);});
test('commands are session/project bound and delivered at most once',async t=>{const f=await fixture(t),s=await f.connect(),id=randomUUID();assert.equal((await f.submit({...s,projectId:'other'},'get_scene',{},id)).status,409);assert.equal((await f.submit(s,'get_scene',{},id)).status,202);assert.equal((await f.submit(s,'get_scene',{},id)).status,409);assert.equal((await(await f.poll(s)).json()).commands[0].id,id);assert.deepEqual((await(await f.poll(s)).json()).commands,[]);assert.equal((await f.result(s,id,scene())).status,200);assert.equal((await f.result(s,id,scene())).status,409);assert.deepEqual((await(await f.request('/commands/'+id)).json()).result,scene());});
test('writes are denied until the paired browser explicitly grants permission',async t=>{const f=await fixture(t),s=await f.connect(),p=await stage(f,s);assert.equal((await f.submit(s,'apply_world',{previewId:p.previewId})).status,403);assert.equal((await f.submit(s,'undo',{})).status,403);assert.equal((await f.request(`/editor/sessions/${s.sessionId}/permissions`,{browser:true,method:'POST',body:{projectId:s.projectId,allowWrites:true}})).status,200);assert.equal((await f.submit(s,'apply_world',{previewId:p.previewId})).status,202);assert.equal((await f.submit(s,'apply_world',{previewId:p.previewId})).status,409);});
test('revoking writes cancels queued mutations and rejects late delivered results',async t=>{const f=await fixture(t),s=await f.connect(true);const q=await(await f.submit(s,'undo')).json();await f.poll(s);await f.request(`/editor/sessions/${s.sessionId}/permissions`,{browser:true,method:'POST',body:{projectId:s.projectId,allowWrites:false}});assert.equal((await(await f.request('/commands/'+q.id)).json()).error.code,'COMMAND_OUTCOME_UNKNOWN');assert.equal((await f.result(s,q.id,{ok:true})).status,409);});
test('reconnect invalidates old sessions, pending commands and staged previews',async t=>{const f=await fixture(t),s=await f.connect(true),p=await stage(f,s),q=await(await f.submit(s)).json();const next=await f.connect(true,'another-project');assert.notEqual(next.sessionId,s.sessionId);assert.equal((await f.poll(s)).status,409);assert.equal((await(await f.request('/commands/'+q.id)).json()).status,'cancelled');assert.equal((await f.submit(next,'apply_world',{previewId:p.previewId})).status,409);});
test('session expires without browser polling even if native status is queried',async t=>{const f=await fixture(t,{sessionIdleMs:30}),s=await f.connect();await delay(50);assert.equal((await(await f.request('/status')).json()).session,null);assert.equal((await f.poll(s)).status,409);});
test('timeout records outcome uncertainty and cannot retry a delivered command',async t=>{
 const f=await fixture(t,{commandTimeoutMs:3000}),s=await f.connect(true),id=randomUUID();
 const submitted=await f.submit(s,'undo',{},id);assert.equal(submitted.status,202);
 const queued=await submitted.json(),polled=await f.poll(s);assert.equal(polled.status,200);
 const batch=await polled.json();assert.equal(batch.commands.length,1);assert.equal(batch.commands[0].id,id);
 // Confirm delivery before waiting for the real deadline; a 30ms deadline could
 // expire in the queue when this file runs alongside the full test suite.
 assert.equal((await(await f.request('/commands/'+id)).json()).status,'delivered');
 await delay(Math.max(0,queued.expiresAt-Date.now())+50);
 const state=await(await f.request('/commands/'+id)).json();assert.equal(state.status,'expired');assert.equal(state.error.code,'COMMAND_OUTCOME_UNKNOWN');
 assert.equal((await f.submit(s,'undo',{},id)).status,409);assert.equal((await f.result(s,id,{ok:true})).status,409);
});
test('cancellation tombstones block a racing late submission',async t=>{const f=await fixture(t),s=await f.connect(true),id=randomUUID();assert.equal((await f.request('/commands/'+id+'/cancel',{method:'POST',body:{}})).status,200);assert.equal((await f.submit(s,'undo',{},id)).status,409);assert.deepEqual((await(await f.poll(s)).json()).commands,[]);});
test('pending queue has a fixed eight command maximum',async t=>{const f=await fixture(t),s=await f.connect();for(let i=0;i<8;i++)assert.equal((await f.submit(s)).status,202);assert.equal((await f.submit(s)).status,429);});
test('body, MIME and arbitrary command schemas fail closed',async t=>{const f=await fixture(t),s=await f.connect();assert.equal((await f.request('/commands',{method:'POST',body:'x'.repeat(524289)})).status,413);assert.equal((await f.request('/commands',{method:'POST',body:{},headers:{'content-type':'text/plain'}})).status,415);for(const [command,args]of[['execute',{code:'evil()'}],['get_scene',{path:'C:/secret'}],['get_scene',{limit:251}],['preview_world',{recipe:{...recipe,script:'evil()'}}],['preview_world',{recipe:{...recipe,operations:[{op:'add',entity:{type:'model',url:'https://evil.test'}}]}}]])assert.equal((await f.submit(s,command,args)).status,400);});
test('preview transport uses the exact engine shape validator including optional scatter defaults',()=>{const value={version:1,seed:1,operations:[{op:'scatter',entity:{type:'box'},count:3,bounds:{min:[0,0],max:[5,5]}}]};assert.equal(validArguments('preview_world',{recipe:value}),true);assert.equal(validArguments('preview_world',{recipe:{...recipe,operations:[{...recipe.operations[0],counts:[51,1]}]}}),false);});
test('result projection rejects asset locations, secrets and arbitrary raw errors',async t=>{const f=await fixture(t),s=await f.connect(),q=await(await f.submit(s)).json();await f.poll(s);const value=scene();value.assets=[{id:'asset',name:'private',mime:'model/gltf-binary',url:'file:///secret'}];assert.equal((await f.result(s,q.id,value)).status,400);const secret=scene();secret.name=f.bridge.token;assert.equal((await f.result(s,q.id,secret)).status,400);const r=await f.request(`/editor/sessions/${s.sessionId}/results`,{browser:true,method:'POST',body:{commandId:q.id,projectId:s.projectId,error:{message:f.bridge.editorToken}}});assert.equal(r.status,200);const state=await(await f.request('/commands/'+q.id)).json();assert.deepEqual(state.error,{code:'EDITOR_REJECTED'});assert.equal(JSON.stringify(state).includes(f.bridge.editorToken),false);});
test('scene projection accepts fixed MIME but excludes provider/legacy metadata',()=>{const p=newProject();p.assets=[{id:'asset',name:'Model',mime:'model/gltf-binary',url:'https://private',cloudId:'private',embedded:'bytes'}];p.legacySource={token:'private'};const projected=sceneContext(p);assert.equal(validResult('get_scene',projected,p.id),true);assert.equal(JSON.stringify(projected).includes('private'),false);});

async function subprocess(t,f){
 const child=spawn(process.execPath,[fileURLToPath(new URL('./mcp-server.mjs',import.meta.url))],{env:{SystemRoot:process.env.SystemRoot,CRATESHIP_EDITOR_TOKEN:f.bridge.token,CRATESHIP_EDITOR_PORT:String(f.address.port)},stdio:['pipe','pipe','pipe'],windowsHide:true});t.after(()=>child.kill());let partial='',stderr='';const waiting=new Map(),responses=[];child.stderr.on('data',x=>stderr+=x);
 child.stdout.on('data',x=>{partial+=x;let n;while((n=partial.indexOf('\n'))>=0){const value=JSON.parse(partial.slice(0,n));partial=partial.slice(n+1);responses.push(value);const waiter=waiting.get(value.id);if(waiter){clearTimeout(waiter.timer);waiting.delete(value.id);waiter.resolve(value);}}});
 const send=message=>child.stdin.write(JSON.stringify({jsonrpc:'2.0',...message})+'\n');
 const rpc=message=>new Promise((resolve,reject)=>{const timer=setTimeout(()=>reject(new Error('MCP timed out: '+stderr)),6000);waiting.set(message.id,{resolve,timer});send(message);});
 const init=async()=>{const r=await rpc({id:1,method:'initialize',params:{protocolVersion:'2025-06-18',capabilities:{},clientInfo:{name:'test',version:'1'}}});assert.equal(r.result.protocolVersion,'2025-06-18');send({method:'notifications/initialized'});};
 return {child,send,rpc,init,responses};
}
test('real stdio subprocess discovers tools and reads through paired browser transport',async t=>{const f=await fixture(t),s=await f.connect(),m=await subprocess(t,f);assert.equal((await m.rpc({id:90,method:'tools/list'})).error.code,-32000);await m.init();const list=await m.rpc({id:2,method:'tools/list'});assert.deepEqual(list.result.tools.map(x=>x.name),['get_scene','preview_world','apply_world','undo']);const pending=m.rpc({id:3,method:'tools/call',params:{name:'get_scene',arguments:{limit:10}}});let command;for(let i=0;i<30&&!command;i++){command=(await(await f.poll(s)).json()).commands[0];if(!command)await delay(20);}assert.ok(command);assert.equal((await f.result(s,command.id,scene())).status,200);const answer=await pending;assert.equal(JSON.parse(answer.result.content[0].text).projectId,s.projectId);assert.equal((await m.rpc({id:3,method:'ping'})).error.code,-32600);});
test('MCP cancellation is handled while a tool is pending and removes queued work',async t=>{const f=await fixture(t),s=await f.connect(),m=await subprocess(t,f);await m.init();m.send({id:2,method:'tools/call',params:{name:'get_scene',arguments:{}}});let command;for(let i=0;i<30&&!command;i++){command=(await(await f.poll(s)).json()).commands[0];if(!command)await delay(20);}assert.ok(command);m.send({method:'notifications/cancelled',params:{requestId:2}});await delay(180);assert.equal((await(await f.request('/commands/'+command.id)).json()).status,'cancelled');assert.ok((await m.rpc({id:3,method:'ping'})).result);assert.equal(m.responses.some(x=>x.id===2),false);});
test('MCP rejects arbitrary execution, per-call credentials and oversized unterminated input',async t=>{const f=await fixture(t),m=await subprocess(t,f);await m.init();for(const [i,params]of[{name:'execute_python',arguments:{code:'evil()'}},{name:'get_scene',arguments:{apiKey:'private'}},{name:'apply_world',arguments:{recipe}}].entries())assert.equal((await m.rpc({id:2+i,method:'tools/call',params})).error.code,-32602);m.child.stdin.write('x'.repeat(524289));await delay(100);assert.ok(m.responses.some(x=>x.error?.message==='MCP input limit exceeded.'));});
test('real bridge plus browser client previews and applies a world as one reversible change',async t=>{
 const f=await fixture(t),store=new ProjectStore(newProject('Live transport test')),cache=new Map();let writes=0;
 const editor={getProject:()=>store.snapshot(),previewWorld:async value=>{const compiled=compileWorldRecipe(value,store.project),preview={previewId:randomUUID(),summary:compiled.summary,entities:compiled.entities};cache.set(preview.previewId,preview);return preview;},applyWorld:async({previewId})=>{const p=cache.get(previewId);if(!p)throw new Error('stale');cache.delete(previewId);store.commit('MCP world',project=>project.entities.push(...p.entities));writes++;},undo:async()=>{store.undo();}};
 const client=createEditorMcpClient({getEditor:()=>editor,getState:()=>({busy:false,mode:'edit'}),autoPoll:false,fetchFn:(url,options)=>fetch(f.base+new URL(url).pathname,{...options,headers:{...options.headers,origin}})});t.after(()=>client.dispose());await client.connect(f.bridge.editorToken,{allowWrites:true});
 async function run(command,args){let done=false;const pending=callEditor(command,args,{token:f.bridge.token,port:f.address.port}).finally(()=>done=true);for(let i=0;i<60&&!done;i++){await client.pollOnce();await delay(15);}return pending;}
 const initial=await run('get_scene',{});assert.equal(initial.entityCount,0);const preview=await run('preview_world',{recipe});assert.equal(preview.entities.length,6);assert.equal(store.project.entities.length,0);await run('apply_world',{previewId:preview.previewId});assert.equal(store.project.entities.length,6);assert.equal(writes,1);assert.equal(store.past.length,1);await run('undo',{});assert.equal(store.project.entities.length,0);
});
