[package]
name = "koko-scripting"
version.workspace = true
edition.workspace = true

[dependencies]
koko-core = { path = "../koko-core" }
tracing = { workspace = true }
serde = { workspace = true }
serde_json = { workspace = true }

[target.'cfg(not(target_arch = "wasm32"))'.dependencies]
mlua = { workspace = true }
